<?php
$installer = $this;
$setup = new Mage_Eav_Model_Entity_Setup('core_setup');
$installer->startSetup();						
$setup->addAttributeGroup('catalog_product', 'Default', 'Wheel and Tyres Attributes', 1000);		


				
$setup->addAttribute('catalog_product', 'customer_segment', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Customer Segment',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									 'optionone' => array('Consumer'),
									 'optiontwo' => array('Commercial'),												
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));


$setup->addAttribute('catalog_product', 'updating_person', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Updated By',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									 'optionone' => array('Andrew'),
									 'optiontwo' => array('Remy'),												
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));



$setup->addAttribute('catalog_product', 'sap_code', array(
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
    'label'         => 'Sap Code',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));

// commented out and added it to mysql4-upgrade-0.6.0-0.7.0.php file with updated dropdown options
// $setup->addAttribute('catalog_product', 'categorization', array(
// 			 'group'     	=> 'Wheel and Tyres Attributes',
// 			 'label'             => 'Categorization',
// 			 'type'              => 'varchar',
// 			 'input'             => 'select',
// 			 'backend'           => 'eav/entity_attribute_backend_array',
// 			 'frontend'          => '',	
// 			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
// 			 'visible'           => true,
// 			 'required'          => true,
// 			 'user_defined'      => true,
// 			 'searchable'        => false,
// 			 'filterable'        => true,
// 			 'comparable'        => false,
// 			 'option'            => array ('value' => 
// 									array(
// 									 'optionone' => array('4x4 - ALL-TERRAIN'),
// 									 'optiontwo' => array('4x4 - ALL-TERRAIN (50% ON-ROAD;  50% OFF-ROAD)'),
// 									 'optionthree' => array('4x4 - ALL-TERRAIN (70% ON-ROAD;  30% OFF-ROAD)'),
// 									 'optionfour' => array('4x4 - HIGHWAY (100% ON-ROAD)'),
// 									 'optionfive' => array('4x4 - HIGHWAY (80% ON-ROAD;  20% OFF-ROAD)'),
// 									 'optionsix' => array('4x4 - HIGHWAY (90% ON-ROAD;  10% OFF-ROAD)'),
// 									 'optionseven' => array('4x4 - OFF-ROAD (10% ON-ROAD;  90% OFF-ROAD)'),
// 									 'optioneight' => array('4x4 - OFF-ROAD (30% ON-ROAD;  70% OFF-ROAD)'),
// 									 'optionnine' => array('4x4 - ON-ROAD (100% ON-ROAD)'),
// 									 'optionten' => array('4x4 - ON-ROAD (50% ON-ROAD;  50% OFF-ROAD)'),
// 									 'optioneleven' => array('4x4 - ON-ROAD (80% ON-ROAD;  20% OFF-ROAD)'),
// 									 'optiontwelve' => array('4x4 - ON-ROAD (90% ON-ROAD;  10% OFF-ROAD)'),
// 									 'optionthirteen' => array('Light Truck'),
// 									 'optionfourteen' => array('Passenger'),
// 									 'optionfiftheen' => array('Truck'),
// 									 'optionsixteen' => array('Passenger '),									 
// 								)
// 							),
// 			 'visible_on_front'  => false,
// 			 'visible_in_advanced_search' => false,
// 			 'unique'            => false
// ));




$setup->addAttribute('catalog_product', 'application', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Application',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('Niche'),
									'optiontwo' => array('Flaship'),
									'optionthree' => array('Standard'),
									'optionfour' => array('LineHaul'),
									'optionfive' => array('Mixed Service'),
									'optionsix' => array('Municipal'),
									'optionseven' => array('Regional Haul'),									 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));





$setup->addAttribute('catalog_product', 'brand', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Brand',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('Dunlop'),
									'optiontwo' => array('Goodyear'),
									'optionthree' => array('Load Runner'),
									'optionfour' => array('Remington'),
									'optionfive' => array('Steelmark'),
									'optionsix' => array('Triangle'),									 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));





$setup->addAttribute('catalog_product', 'tire_size', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Sizes',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
											'option1'=>array('106V'),
											'option2'=>array('107Y XL'),
											'option3'=>array('109W XL'),
											'option4'=>array('110W XL'),
											'option5'=>array('110Y XL'),
											'option6'=>array('100H'),
											'option7'=>array('100T'),
											'option8'=>array('102H'),
											'option9'=>array('103T'),
											'option10'=>array('104S'),
											'option11'=>array('108S XL'),
											'option12'=>array('109H'),
											'option13'=>array('109S'),
											'option14'=>array('109T XL'),
											'option15'=>array('110/107S'),
											'option16'=>array('110H'),
											'option17'=>array('111S XL'),
											'option18'=>array('111T'),
											'option19'=>array('111T XL'),
											'option20'=>array('112/109S'),
											'option21'=>array('112S'),
											'option22'=>array('112T'),
											'option23'=>array('114T'),
											'option24'=>array('115H'),
											'option25'=>array('116H'),
											'option26'=>array('117T'),
											'option27'=>array('120H XL'),
											'option28'=>array('122/119Q'),
											'option29'=>array('96H'),
											'option30'=>array('96T'),
											'option31'=>array('98H'),
											'option32'=>array('109R'),
											'option33'=>array('115R'),
											'option34'=>array('112/110R 8PR'),
											'option35'=>array('107T'),
											'option36'=>array('104R'),
											'option37'=>array('113T'),
											'option38'=>array('102T'),
											'option39'=>array('106T'),
											'option40'=>array('108T'),
											'option41'=>array('110/107R'),
											'option42'=>array('112/110R'),
											'option43'=>array('114/111R'),
											'option44'=>array('114/112R'),
											'option45'=>array('115T'),
											'option46'=>array('116T'),
											'option47'=>array('110/108Q'),
											'option48'=>array('123/120R'),
											'option49'=>array('106V XL'),
											'option50'=>array('95H'),
											'option51'=>array('18'),
											'option52'=>array('19'),
											'option53'=>array('20'),
											'option54'=>array('21'),
											'option55'=>array('108/106S'),
											'option56'=>array('108S'),
											'option57'=>array('110S'),
											'option58'=>array('111H'),
											'option59'=>array('115S'),
											'option60'=>array('116V'),
											'option61'=>array('101H'),
											'option62'=>array('103H'),
											'option63'=>array('103S'),
											'option64'=>array('108V XL'),
											'option65'=>array('109V XL'),
											'option66'=>array('112H'),
											'option67'=>array('112V'),
											'option68'=>array('114H'),
											'option69'=>array('95S'),
											'option70'=>array('98S'),
											'option71'=>array('98V'),
											'option72'=>array('99H'),
											'option73'=>array('99S'),
											'option74'=>array('99V'),
											'option75'=>array('107S'),
											'option76'=>array('98T'),
											'option77'=>array('108Q'),
											'option78'=>array('109Q'),
											'option79'=>array('113Q'),
											'option80'=>array('120Q'),
											'option81'=>array('121Q'),
											'option82'=>array('123Q'),
											'option83'=>array('124Q'),
											'option84'=>array('126Q'),
											'option85'=>array('112/110N'),
											'option86'=>array('118/116L'),
											'option87'=>array('106/104N'),
											'option88'=>array('112/100N'),
											'option89'=>array('114/111Q'),
											'option90'=>array('114/112N'),
											'option91'=>array('104/101Q'),
											'option92'=>array('111S'),
											'option93'=>array('115/112Q'),
											'option94'=>array('119/116Q'),
											'option95'=>array('120/116Q'),
											'option96'=>array('121/118Q'),
											'option97'=>array('123/120Q'),
											'option98'=>array('126/123P'),
											'option99'=>array('102V XL'),
											'option100'=>array('110V XL'),
											'option101'=>array('112/110S'),
											'option102'=>array('110T'),
											'option103'=>array('115/112R'),
											'option104'=>array('120/116R'),
											'option105'=>array('120/116S'),
											'option106'=>array('121/118R'),
											'option107'=>array('121/118S'),
											'option108'=>array('124/121S'),
											'option109'=>array('104T'),
											'option110'=>array('104V'),
											'option111'=>array('104V XL'),
											'option112'=>array('102V'),
											'option113'=>array('103V'),
											'option114'=>array('104H'),
											'option115'=>array('104H XL'),
											'option116'=>array('105V XL'),
											'option117'=>array('106H'),
											'option118'=>array('107H'),
											'option119'=>array('107V'),
											'option120'=>array('107V XL'),
											'option121'=>array('108H'),
											'option122'=>array('111H XL'),
											'option123'=>array('112V XL'),
											'option124'=>array('97V'),
											'option125'=>array('105H'),
											'option126'=>array('111V XL'),
											'option127'=>array('101W'),
											'option128'=>array('104W'),
											'option129'=>array('99W XL'),
											'option130'=>array('100/98T'),
											'option131'=>array('101Y'),
											'option132'=>array('102/100P'),
											'option133'=>array('102/100R'),
											'option134'=>array('103/101T'),
											'option135'=>array('104/102R'),
											'option136'=>array('106/104P'),
											'option137'=>array('106/104R'),
											'option138'=>array('106/104T'),
											'option139'=>array('107/105R'),
											'option140'=>array('109/107S'),
											'option141'=>array('110/108R'),
											'option142'=>array('112R'),
											'option143'=>array('113/111R'),
											'option144'=>array('99Y'),
											'option145'=>array('107/105T'),
											'option146'=>array('115/113R'),
											'option147'=>array('106/104S'),
											'option148'=>array('88/86R'),
											'option149'=>array('285/65R16'),
											'option150'=>array('215/60R17'),
											'option151'=>array('165R13'),
											'option152'=>array('175R13'),
											'option153'=>array('205/65R16'),
											'option154'=>array('225/65R16'),
											'option155'=>array('235/65R16'),
											'option156'=>array('205/70R15'),
											'option157'=>array('205/75R14'),
											'option158'=>array('215/65R15'),
											'option159'=>array('215/70R15'),
											'option160'=>array('104/102S'),
											'option161'=>array('100W XL'),
											'option162'=>array('82V'),
											'option163'=>array('84W XL'),
											'option164'=>array('85V'),
											'option165'=>array('87V'),
											'option166'=>array('87W XL'),
											'option167'=>array('88W XL'),
											'option168'=>array('91V'),
											'option169'=>array('91W'),
											'option170'=>array('91W XL'),
											'option171'=>array('92V'),
											'option172'=>array('92W XL'),
											'option173'=>array('93V'),
											'option174'=>array('93W XL'),
											'option175'=>array('94V'),
											'option176'=>array('94W'),
											'option177'=>array('94W XL'),
											'option178'=>array('95V'),
											'option179'=>array('95W'),
											'option180'=>array('95W XL'),
											'option181'=>array('97W XL'),
											'option182'=>array('99W'),
											'option183'=>array('100Y XL'),
											'option184'=>array('103W XL'),
											'option185'=>array('103Y'),
											'option186'=>array('109H XL'),
											'option187'=>array('84T'),
											'option188'=>array('84V'),
											'option189'=>array('84W'),
											'option190'=>array('85Y'),
											'option191'=>array('87H'),
											'option192'=>array('88Y'),
											'option193'=>array('89W XL'),
											'option194'=>array('90Y XL'),
											'option195'=>array('93Y'),
											'option196'=>array('93Y XL'),
											'option197'=>array('94Y'),
											'option198'=>array('95Y'),
											'option199'=>array('96Y'),
											'option200'=>array('98Y XL'),
											'option201'=>array('81H'),
											'option202'=>array('82H'),
											'option203'=>array('86V'),
											'option204'=>array('88V'),
											'option205'=>array('87W'),
											'option206'=>array('91H'),
											'option207'=>array('92W'),
											'option208'=>array('97W'),
											'option209'=>array('98W'),
											'option210'=>array('99V XL'),
											'option211'=>array('100V'),
											'option212'=>array('83W'),
											'option213'=>array('86H'),
											'option214'=>array('88H'),
											'option215'=>array('89H'),
											'option216'=>array('89V'),
											'option217'=>array('92H'),
											'option218'=>array('94H'),
											'option219'=>array('102Y XL'),
											'option220'=>array('104Y'),
											'option221'=>array('105Y XL'),
											'option222'=>array('106W XL'),
											'option223'=>array('107Y'),
											'option224'=>array('108Y'),
											'option225'=>array('109W'),
											'option226'=>array('111V'),
											'option227'=>array('87V XL'),
											'option228'=>array('96Y XL'),
											'option229'=>array('97Y XL'),
											'option230'=>array('ZR'),
											'option231'=>array('113W XL'),
											'option232'=>array('99Y XL'),
											'option233'=>array('100W'),
											'option234'=>array('100Y'),
											'option235'=>array('101Y XL'),
											'option236'=>array('102Y'),
											'option237'=>array('103Y XL'),
											'option238'=>array('104Y XL'),
											'option239'=>array('108Y XL'),
											'option240'=>array('88Y XL'),
											'option241'=>array('89Y XL'),
											'option242'=>array('91Y'),
											'option243'=>array('91Y XL'),
											'option244'=>array('92Y XL'),
											'option245'=>array('94Y XL'),
											'option246'=>array('95Y XL'),
											'option247'=>array('96V'),
											'option248'=>array('96W'),
											'option249'=>array('97Y'),
											'option250'=>array('98Y'),
											'option251'=>array('89W'),
											'option252'=>array('86Y XL'),
											'option253'=>array('92Y'),
											'option254'=>array('93Y '),
											'option255'=>array('88T'),
											'option256'=>array('77V'),
											'option257'=>array('83V'),
											'option258'=>array('79S'),
											'option259'=>array('84H'),
											'option260'=>array('72S'),
											'option261'=>array('80W'),
											'option262'=>array('73S'),
											'option263'=>array('81S'),
											'option264'=>array('92S'),
											'option266'=>array('175/65R14'),
											'option267'=>array('185/55R15'),
											'option268'=>array('185/60R14'),
											'option269'=>array('185/60R15'),
											'option270'=>array('185/65R14'),
											'option271'=>array('185/65R15'),
											'option272'=>array('195/50R15'),
											'option273'=>array('195/50R16'),
											'option274'=>array('195/55R15'),
											'option275'=>array('195/60R14'),
											'option276'=>array('195/60R15'),
											'option277'=>array('195/65R14'),
											'option278'=>array('195/65R15'),
											'option279'=>array('205/50R17'),
											'option280'=>array('205/55R16'),
											'option281'=>array('205/60R16'),
											'option282'=>array('205/65R15'),
											'option283'=>array('215/45R17'),
											'option284'=>array('215/50R17'),
											'option285'=>array('215/55R17'),
											'option286'=>array('215/60R16'),
											'option287'=>array('225/45R17'),
											'option288'=>array('225/50R17'),
											'option289'=>array('225/55R16'),
											'option290'=>array('225/55R17'),
											'option291'=>array('225/60R16'),
											'option292'=>array('235/45R17'),
											'option293'=>array('155/70R13'),
											'option294'=>array('175/65R15'),
											'option295'=>array('175/70R13'),
											'option296'=>array('185/70R14'),
											'option297'=>array('195/70R14'),
											'option298'=>array('195/60R16'),
											'option299'=>array('215/65R16'),
											'option300'=>array('225/45R18'),
											'option301'=>array('235/45R19'),
											'option302'=>array('235/50R17'),
											'option303'=>array('235/55R18'),
											'option304'=>array('245/45R17'),
											'option305'=>array('245/45R18'),
											'option306'=>array('245/45R19'),
											'option307'=>array('245/50R18'),
											'option308'=>array('255/40R18'),
											'option309'=>array('255/45R18'),
											'option310'=>array('255/45R20'),
											'option311'=>array('275/40R19'),
											'option312'=>array('285/40R20'),
											'option313'=>array('205/55R17'),
											'option314'=>array('225/35R18'),
											'option315'=>array('245/35R19'),
											'option316'=>array('245/35R20'),
											'option317'=>array('245/40R18'),
											'option318'=>array('245/40R19'),
											'option319'=>array('255/40R19'),
											'option320'=>array('255/45R19'),
											'option321'=>array('265/35R19'),
											'option322'=>array('265/40R20'),
											'option323'=>array('285/40R19'),
											'option324'=>array('205/45R17'),
											'option325'=>array('225/35R19'),
											'option326'=>array('225/40R18'),
											'option327'=>array('225/40R19'),
											'option328'=>array('235/35R19'),
											'option329'=>array('235/40R18'),
											'option330'=>array('235/40R19'),
											'option331'=>array('235/45R18'),
											'option332'=>array('245/35R18'),
											'option333'=>array('245/40R17'),
											'option334'=>array('245/40R20'),
											'option335'=>array('255/30R19'),
											'option336'=>array('255/35R18'),
											'option337'=>array('255/35R19'),
											'option338'=>array('255/40R17'),
											'option339'=>array('255/40R20'),
											'option340'=>array('265/30R19'),
											'option341'=>array('265/35R18'),
											'option342'=>array('265/40R18'),
											'option343'=>array('265/40R19'),
											'option344'=>array('265/45R18'),
											'option345'=>array('275/30R19'),
											'option346'=>array('275/35R20'),
											'option347'=>array('285/35R18'),
											'option348'=>array('285/35R19'),
											'option349'=>array('205/45R16'),
											'option350'=>array('205/50R16'),
											'option351'=>array('215/40R17'),
											'option352'=>array('215/45R18'),
											'option353'=>array('225/50R16'),
											'option354'=>array('255/50R19'),
											'option355'=>array('255/55R18'),
											'option356'=>array('215/55R16'),
											'option357'=>array('195/55R16'),
											'option358'=>array('235/55R17'),
											'option359'=>array('235/55R19'),
											'option360'=>array('235/60R18'),
											'option361'=>array('245/55R17'),
											'option362'=>array('275/35R19'),
											'option363'=>array('275/40R20'),
											'option364'=>array('165/70R13'),
											'option365'=>array('165/75R13'),
											'option366'=>array('185/75R14'),
											'option367'=>array('185R14C'),
											'option368'=>array('215/70R16'),
											'option369'=>array('225/60R17'),
											'option370'=>array('225/65R17'),
											'option371'=>array('235/60R17'),
											'option372'=>array('245/70R16'),
											'option373'=>array('205/60R15'),
											'option374'=>array('165/60R15'),
											'option375'=>array('175/70R14'),
											'option376'=>array('245/45R20'),
											'option377'=>array('155/65R14'),
											'option378'=>array('165/70R14'),
											'option379'=>array('205/45R18'),
											'option380'=>array('255/50R21'),
											'option381'=>array('285/45R21'),
									 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));



$setup->addAttribute('catalog_product', 'aspect_ratio', array(
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
    'label'         => 'Aspect Ratio',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));

$setup->addAttribute('catalog_product', 'rim', array(
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
    'label'         => 'Rim',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));



$setup->addAttribute('catalog_product', 'position_wheels', array(
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
    'label'         => 'Position Wheels',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));

$setup->addAttribute('catalog_product', 'oe', array(
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
    'label'         => 'OE',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));

// deleted and was updated in mysql4-upgrade-0.6.0-0.7.0.php file
// $setup->addAttribute('catalog_product', 'run_flat', array(
// 	'group'     	=> 'Wheel and Tyres Attributes',
// 	'input'         => 'text',
//     'type'          => 'text',
//     'label'         => 'Run Flat',
// 	'backend'       => '',
// 	'visible'       => 1,
// 	'required'		=> 0,
// 	'user_defined' => 1,
// 	'searchable' => 1,
// 	'filterable' => 0,
// 	'comparable'	=> 1,
// 	'visible_on_front' => 1,
// 	'visible_in_advanced_search'  => 0,
// 	'is_html_allowed_on_front' => 0,
//     'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
// ));

// $setup->addAttribute('catalog_product', 'run_flat', array(
// 	'group'     	=> 'Wheel and Tyres Attributes',
// 	'input'         => 'text',
//     'type'          => 'text',
//     'label'         => 'Run Flat',
// 	'backend'       => '',
// 	'visible'       => 1,
// 	'required'		=> 0,
// 	'user_defined' => 1,
// 	'searchable' => 1,
// 	'filterable' => 0,
// 	'comparable'	=> 1,
// 	'visible_on_front' => 1,
// 	'visible_in_advanced_search'  => 0,
// 	'is_html_allowed_on_front' => 0,
//     'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
// ));





$setup->addAttribute('catalog_product', 'durability', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Durability',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));


$setup->addAttribute('catalog_product', 'handling', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Handling',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));

$setup->addAttribute('catalog_product', 'sport_performance', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Sports Performance',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));

$setup->addAttribute('catalog_product', 'wet_weather', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Wet Weather',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));

$setup->addAttribute('catalog_product', 'fuel_saver', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Fuel Saver',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));


$setup->addAttribute('catalog_product', 'off_road', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Off-Road',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));


$setup->addAttribute('catalog_product', 'superior_braking', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Braking',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));




$setup->addAttribute('catalog_product', 'grip', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Grip',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));

$setup->addAttribute('catalog_product', 'quiet', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Quiet',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));

$setup->addAttribute('catalog_product', 'mileage', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Mileage (Slow Ware)',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));

$setup->addAttribute('catalog_product', 'even_ware', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Even Ware',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));

$setup->addAttribute('catalog_product', 'comfort', array(
			 'group'     	=> 'Wheel and Tyres Attributes',
			 'label'             => 'Comfort',
			 'type'              => 'varchar',
			 'input'             => 'select',
			 'backend'           => 'eav/entity_attribute_backend_array',
			 'frontend'          => '',	
			 'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
			 'visible'           => true,
			 'required'          => true,
			 'user_defined'      => true,
			 'searchable'        => false,
			 'filterable'        => true,
			 'comparable'        => false,
			 'option'            => array ('value' => 
									array(
									'optionone' => array('0'),
									'optiontwo' => array('1'),
									'optionthree' => array('2'),
									'optionfour' => array('3'),								 
								)
							),
			 'visible_on_front'  => false,
			 'visible_in_advanced_search' => false,
			 'unique'            => false
));




$setup->addAttribute('catalog_product', 'load_index', array(
    'label'         => 'Load Index',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));


$setup->addAttribute('catalog_product', 'speed_rating', array(
    'label'         => 'Speed Rating',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));



$setup->addAttribute('catalog_product', 'overall_diameter', array(
    'label'         => 'Overall Diameter',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));

$setup->addAttribute('catalog_product', 'tread_depth', array(
    'label'         => 'Tread Depth (mm)',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));


$setup->addAttribute('catalog_product', 'static_loaded_radius', array(
    'label'         => 'Static Loaded Radius (mm)',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));


$setup->addAttribute('catalog_product', 'revs_per_km', array(
    'label'         => 'Revs per km',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));


$setup->addAttribute('catalog_product', 'measuring_rim', array(
    'label'         => 'Measuring Rim',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));


$setup->addAttribute('catalog_product', 'other_perimissable_rims', array(
    'label'         => 'Other Permissable Rims',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));



$setup->addAttribute('catalog_product', 'overall_weight', array(
    'label'         => 'Overall width',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));

$setup->addAttribute('catalog_product', 'compliance', array(
    'label'         => 'Compliance',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));

$setup->addAttribute('catalog_product', 'radial_diagonal', array(
    'label'         => 'Radial Diagonal',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'text',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));



// used existing product attribute ( description )
// $setup->addAttribute('catalog_product', 'product_description', array(
//     'label'         => 'Product Description',
// 	'group'     	=> 'Wheel and Tyres Attributes',
// 	'input'         => 'textarea',
//     'type'          => 'text',
// 	'backend'       => '',
// 	'visible'       => 1,
// 	'required'		=> 0,
// 	'user_defined' => 1,
// 	'searchable' => 1,
// 	'filterable' => 0,
// 	'comparable'	=> 1,
// 	'visible_on_front' => 1,
// 	'visible_in_advanced_search'  => 0,
// 	'is_html_allowed_on_front' => 0,
//     'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
// ));


$setup->addAttribute('catalog_product', 'benefits_description', array(
    'label'         => 'Benefits Description',
	'group'     	=> 'Wheel and Tyres Attributes',
	'input'         => 'textarea',
    'type'          => 'text',
	'backend'       => '',
	'visible'       => 1,
	'required'		=> 0,
	'user_defined' => 1,
	'searchable' => 1,
	'filterable' => 0,
	'comparable'	=> 1,
	'visible_on_front' => 1,
	'visible_in_advanced_search'  => 0,
	'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));

$installer->endSetup();