<?php
/**
 * Magento Enterprise Edition
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the The MIT License Agreement
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to mmansuri@apdgroup.com so I can send you a copy immediately.
 *
 * @category    design
 * @package     default_apdinteract
 * @copyright Copyright (c) 2017 Mohib Mansuri
 * @license https://opensource.org/licenses/MIT
 */
?>
<p class="bug-report">
    <a href="<?php echo $this->getBugreportUrl() ?>" id="footer_bug_tracking"><?php echo $this->__('Help Us Keep Magento Healthy - Report All Bugs') ?></a><br/>
</p>
<p class="legality">
    <a href="<?php echo $this->getConnectWithMagentoUrl() ?>" id="footer_connect"><?php echo $this->__('Connect with the Magento Community') ?></a><br/>
    <img src="<?php echo $this->getSkinUrl('images/varien_logo.gif') ?>" class="v-middle" alt="" />&nbsp;&nbsp;
    <?php echo $this->__('Magento&trade; is a trademark of Magento Inc.<br/>Copyright &copy; %s Magento Inc.', date('Y')) ?>
</p>
<?php echo $this->__('Magento ver. %s', Mage::getVersion()) ?>
<script type="text/javascript">
    $('footer_bug_tracking').target = 'Varien_External';
    $('footer_connect').target = 'Varien_External';
</script>
