<?php
// Mage::getSingleton('core/session')->unsetData('product_code_wheels');
// print_r(Mage::getSingleton('core/session')->getData());


$storelocatorUrl = Mage::getBaseUrl() . Mage::helper('storelocator')->getRoute() . '/';
$countryCode = (Mage::getStoreConfig('general/country/default') != '' ? strtolower(Mage::getStoreConfig('general/country/default')) : 'au');
?>
<div class="sticky-header">
<div class="sticky-container">
<?php echo $this->getChildHtml('custom_toplink') ?>
<header class="main-header">
  <script id="header-icons-config" type="application/json">
    [
      {
        "label": "Search",
        "icon": "fa-search",
        "showLabel": false,
        "isActive": false,
        "isToggle": true,
        "link": null,
        "action": "toggleSearch",
        "visibility": "all",
        "badge": 0
      },
      <?php  if(!Mage::getSingleton('customer/session')->isLoggedIn()):?>
      {
        "label": "Login",
        "icon": "fa-user-o",
        "showLabel": false,
        "isActive": false,
        "isToggle": true,
        "link": null,
        "action": "toggleLogin",
        "visibility": "desktop",
        "badge": 0
      },
     <?php else :?>
      {
        "label": "Account",
        "icon": "fa-user",
        "showLabel": false,
        "isActive": false,
        "isToggle": true,
        "link": null,
        "action": "toggleAccount",
        "visibility": "desktop",
        "badge": 0
      },
     <?php endif;?>
      {
        "label": "Call",
        "icon": "fa-phone",
        "showLabel": false,
        "isActive": false,
        "isToggle": false,
        "link": "tel:1800185099",
        "action": null,
        "visibility": "mobile",
        "badge": 0
      },
      {
        "label": "Cart",
        "icon": "fa-shopping-cart",
        "showLabel": false,
        "isActive": false,
        "isToggle": true,
        "link": null,
        "action": "toggleCart",
        "visibility": "all",
        "badge": <?php if(Mage::helper('checkout/cart')->getSummaryCount()>0) { echo Mage::helper('checkout/cart')->getSummaryCount(); }else { echo '0';} ?>
      }
    ]
  </script>
<main-header header-title="<?php echo $this->getLogoAlt() ?>"
  header-icons-config-id="header-icons-config"
  search-panel-text="<?php echo $this->__("Search entire store here...")?>"
  search-panel-input-name="q"
  search-panel-action="/catalogsearch/result/"
  search-panel-no-result="No results!"
  search-connection-error="Request failed/error"
  search-view-all="/catalogsearch/result/?q="
  search-api="/searchautocomplete/ajax/get/?q="
  login-login-text="<?php echo $this->__("Log In")?>"
  login-login-icon="fa-sign-in"
  login-login-url="<?php echo Mage::getUrl('customer/account/loginPost/'); ?>"
  login-forgot-password="<?php echo Mage::getUrl('customer/account/forgotpassword'); ?>"
  login-signup-text="<?php echo $this->__("Register")?>"
  login-signup-icon="fa-user-plus"
  login-signup-url="<?php echo Mage::getUrl('customer/account/create'); ?>"
   login-social-fb-url="<?php echo Mage::getUrl('pslogin/account/use', array('type' => 'facebook')) ?>"
   login-social-fb-popup-width="650"
   login-social-fb-popup-height="35"
   login-social-google-url="<?php echo Mage::getUrl('pslogin/account/use', array('type' => 'googleplus')) ?>"
   login-social-google-popup-width="650"
   login-social-google-popup-height="350" 
  account-my-account-text="<?php echo $this->__("My Account Dashboard")?>"
  account-formkey="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
  account-my-account-icon="fa-address-card-o"
  account-my-account-url="<?php echo Mage::getUrl('customer/account'); ?>"
  account-logout-text="<?php echo $this->__("Logout")?>"
  account-logout-icon="fa-sign-out"
  account-logout-url="<?php echo Mage::getUrl('customer/account/logout'); ?>"
  minicart-display-url="/checkout/cart/ajaxDisplay"
  minicart-update-url="/checkout/cart/ajaxUpdate"
  minicart-delete-url="/checkout/cart/ajaxDelete"
  minicart-checkout-url="/checkout/onepage"
  minicart-cart-url="/checkout/cart"
  minicart-change-store-url="/store-locator"
  >

  <!-- Content replaced by main-header compontent.  Content added for SEO only  -->
  <h1><?php echo $this->getLogoAlt() ?></h1>
  <a href="tell:1800185099">Call Us: 1800 185 099</a>
  <a href="<?php echo Mage::getUrl('customer/account/login'); ?>"><?php echo $this->__("Log In")?></a>
  <a href="<?php echo Mage::getUrl('customer/account/create'); ?>"><?php echo $this->__("Register")?></a>
</main-header>
 </header>
<?php echo $this->getChildHtml('topMenu') ?>
</div>
</div>
<?php echo $this->getChildHtml('vehicle_selector') ?>