<?php
/**
 * Check whether description needs to be truncated or not
 */

?>
<?php $_product = $this->getProduct(); ?>
<?php $shortDescription = $_product->getShortDescription()?>
<?php if ($shortDescription):?>
	<?php $shortDesc = $this->helper('catalog/output')->productAttribute($this->getProduct(), $shortDescription, 'short_description') ?>
	<?php $count = strlen($shortDesc)?>
		<?php if ($count > 90):?>
	    <?php $truncated = substr($shortDesc, 0,90)?>
	    <div class="show-for-small-only show-less">
			<div class="collapsed">
				<?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $truncated, 'short_description') ?><a href="javascript:void(0)" id="readMore" class="pdp-readmore"><?php echo $this->__(' Read More')?></a>
			</div>
			<div class="expanded hide">
			 <?php echo strip_tags($this->helper('catalog/output')->productAttribute($this->getProduct(), $shortDescription, 'short_description')) ?><a href="javascript:void(0)" id="readLess" class="pdp-readmore"><?php echo $this->__(' Show Less')?></a>
			</div>
			<br/>
		</div>
		<div class="show-for-desktop-only"><?php echo $shortDesc ?></div>
		<?php else:?>
	    <div><?php echo $shortDesc ?></div>
	    <?php endif; ?>
<?php endif; ?>
