<?php
   $_helper = $this->helper('catalog/product_compare');
   $_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
   ?>
<?php if ($_items): ?>
<div class="row show-for-large-up">
   <div class="small-12 columns">
      <div class="comp-compare-products">
         <h3><?php echo $this->__('Compare Products') ?>
            <?php if($_helper->getItemCount() > 0): ?>
            <?php echo $this->__('(%d)', $_helper->getItemCount()) ?>
            <?php endif; ?>
         </h3>
         <?php if($_helper->getItemCount() > 0): ?>
         <ul class="no-bullet">
            <?php foreach($_items as $_index => $_item): ?>
            <li>
               <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
               <?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?> <a href="<?php echo $_helper->getRemoveUrl($_item) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>" class="btn-remove" onclick="return confirm('<?php echo Mage::helper('core')->quoteEscape($this->__('Are you sure you would like to remove this item from the compare products?')) ?>');"><i class="right fa fa-fw fa-lg fa-times-circle"></i></a>
            </li>
            <?php endforeach; ?>
         </ul>
<!--         <script type="text/javascript">decorateList('compare-items')</script>-->
         <div class="row">
            <div class="small-5 columns">
            	<div class="action">
               <a href="<?php echo $_helper->getClearListUrl() ?>" onclick="return confirm('<?php echo Mage::helper('core')->quoteEscape($this->__('Are you sure you would like to remove all products from your comparison?')) ?>');"><?php echo $this->__('Clear All') ?></a>
               </div>
            </div>
            <div class="small-7 columns text-right">
               <input type="button" class="small radius button" onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')" value="<?php echo $this->__('Compare') ?>">
            </div>
         </div>
         <?php else: ?>
         <p class="empty"><?php echo $this->__('You have no items to compare.') ?></p>
         <?php endif; ?>
      </div>
   </div>
</div>
<?php endif; ?>
