<?php
class ApdInteract_Stock_Helper_Data extends Mage_Core_Helper_Abstract
{    
	public function updateCostarCode(){
		$data = array(
				"U101"=>array("MINTO"=>"NSW"),
				"U104"=>array("PORT KEMBLA"=>"NSW"),
				"U106"=>array("N%TH%RICHMOND"=>"NSW"),
				"U108"=>array("SILVERWATER"=>"NSW"),
				"U111"=>array("EASTERN CREEK"=>"NSW"),
				"U113"=>array("BANKSTOWN"=>"NSW"),
				"U114"=>array("BROOKVALE"=>"NSW"),
				"U115"=>array("BLACKTOWN"=>"NSW"),
				"U116"=>array("CROWS NEST"=>"NSW"),
				"U118"=>array("GOUGER ST"=>"SA"),
				"U119"=>array("STRATHALBYN"=>"SA"),
				"U120"=>array("ARUNDEL"=>"QLD"),
				"U122"=>array("MELVILLE"=>"WA"),
				"U123"=>array("MASCOT"=>"NSW"),
				"U126"=>array("RAYMOND TERRACE"=>"NSW"),
				"U127"=>array("GRAFTON"=>"NSW"),
				"U128"=>array("COFFS HARBOUR"=>"NSW"),
				"U131"=>array("PENRITH%WOODRIFF"=>"NSW"),
				"U132"=>array("PYMBLE"=>"NSW"),
				"U135"=>array("RYDE"=>"NSW"),
				"U136"=>array("TUMUT"=>"NSW"),
				"U137"=>array("TAREN POINT"=>"NSW"),
				"U141"=>array("HORNSBY"=>"NSW"),
				"U142"=>array("GOSFORD"=>"NSW"),
				"U144"=>array("GRENFELL"=>"NSW"),
				"U145"=>array("MOREE"=>"NSW"),
				"U147"=>array("MAROUBRA"=>"NSW"),
				"U150"=>array("THORNTON"=>"NSW"),
				"U151"=>array("ORANGE"=>"NSW"),
				"U153"=>array("PICTON"=>"NSW"),
				"U154"=>array("MUSWELLBROOK"=>"NSW"),
				"U155"=>array("OSBORNE PARK%COMMERCIAL"=>"WA"),
				"U156"=>array("CASTLE HILL"=>"NSW"),
				"U158"=>array("YASS"=>"NSW"),
				"U159"=>array("KOTARA"=>"NSW"),
				"U160"=>array("FYSHWICK"=>"ACT"),
				"U161"=>array("COOTAMUNDRA"=>"NSW"),
				"U162"=>array("Cheltenham"=>"VIC"),
				"U163"=>array("Malvern"=>"VIC"),
				"U164"=>array("KEMPSEY"=>"NSW"),
				"U165"=>array("YEAR AUTOCARE - GOSFORD"=>"NSW"),
				"U170"=>array("WAGGA"=>"NSW"),
				"U172"=>array("WEST WYALONG"=>"NSW"),
				"U173"=>array("NARRANDERA"=>"NSW"),
				"U175"=>array("TOORMINA"=>"NSW"),
				"U179"=>array("BROCKLEHURST"=>"NSW"),
				"U180"=>array("CHATSWOOD"=>"NSW"),
				"U182"=>array("RUTHERFORD"=>"NSW"),
				"U186"=>array("YOUNG RETAIL"=>"NSW"),
				"U190"=>array("YOUNG%COMMERCIAL"=>"NSW"),
				"U194"=>array("BALLINA"=>"NSW"),
				"U201"=>array("PENNANT HILLS"=>"NSW"),
				"U202"=>array("FRANKSTON"=>"VIC"),
				"U203"=>array("YARRAVILLE"=>"VIC"),
				"U204"=>array("SCOTTSDALE"=>"TAS"),
				"U205"=>array("SOUTH MELBOURNE"=>"VIC"),
				"U206"=>array("KEW"=>"VIC"),
				"U207"=>array("CARLTON"=>"VIC"),
				"U208"=>array("PORT MELBOURNE"=>"VIC"),
				"U213"=>array("EASTERN HUB"=>"VIC"),
				"U214"=>array("FOUNTAIN GATE"=>"VIC"),
				"U224"=>array("WESTALL RD"=>"VIC"),
				"U226"=>array("SOMERTON"=>"VIC"),
				"U230"=>array("BAYSWATER%COMMERCIAL"=>"VIC"),
				"U233"=>array("SOUTH MORANG"=>"VIC"),
				"U234"=>array("Alphington"=>"VIC"),
				"U235"=>array("CLAYTON"=>"VIC"),
				"U238"=>array("SOUTH YARRA"=>"VIC"),
				"U239"=>array("NORTH ALBURY"=>"NSW"),
				"U240"=>array("GUNGAHLIN"=>"ACT"),
				"U241"=>array("WODONGA"=>"VIC"),
				"U245"=>array("DENILIQUIN"=>"NSW"),
				"U246"=>array("FERNTREE GULLY"=>"VIC"),
				"U247"=>array("BENALLA"=>"VIC"),
				"U253"=>array("CRANBOURNE"=>"VIC"),
				"U255"=>array("DANDENONG"=>"VIC"),
				"U259"=>array("COLAC"=>"VIC"),
				"U260"=>array("PAKENHAM"=>"VIC"),
				"U261"=>array("DONCASTER"=>"VIC"),
				"U262"=>array("HOPPERS CROSSING"=>"VIC"),
				"U263"=>array("BRAESIDE"=>"VIC"),
				"U264"=>array("SWAN HILL"=>"VIC"),
				"U265"=>array("BENDIGO"=>"VIC"),
				"U268"=>array("HAWTHORN"=>"VIC"),
				"U269"=>array("NORTH GEELONG"=>"VIC"),
				"U270"=>array("KILMORE"=>"VIC"),
				"U271"=>array("HAMILTON"=>"VIC"),
				"U274"=>array("MORNINGTON%CO"=>"VIC"),
				"U275"=>array("GREENSBOROUGH"=>"VIC"),
				"U276"=>array("EPPING"=>"VIC"),
				"U278"=>array("WEST MELBOURNE"=>"VIC"),
				"U280"=>array("LAVERTON"=>"VIC"),
				"U281"=>array("BURNIE"=>"TAS"),
				"U282"=>array("SMITHTON"=>"TAS"),
				"U283"=>array("DEVONPORT"=>"TAS"),
				"U284"=>array("INVERMAY"=>"TAS"),
				"U285"=>array("NEW NORFOLK"=>"TAS"),
				"U286"=>array("HOBART"=>"TAS"),
				"U287"=>array("MOONAH"=>"TAS"),
				"U294"=>array(" OFFICE CHARGEBACK"=>"VIC"),
				"U301"=>array("BROWNS PLAINS"=>"QLD"),
				"U308"=>array("LOGANHOLME"=>"QLD"),
				"U312"=>array("WOOLLOONGABBA"=>"QLD"),
				"U315"=>array("MITCHELTON"=>"QLD"),
				"U317"=>array("TOWNSVILLE%COMMERCIAL"=>"QLD"),
				"U319"=>array("MOBILE CLONCURRY"=>"QLD"),
				"U325"=>array("KEPERRA"=>"QLD"),
				"U326"=>array("MORNINGSIDE"=>"QLD"),
				"U327"=>array("NOOSAVILLE"=>"QLD"),
				"U328"=>array("FORTITUDE VAL"=>"QLD"),
				"U335"=>array("WYNNUM"=>"QLD"),
				"U341"=>array("MALAGA"=>"WA"),
				"U351"=>array("MACKAY CENTRA"=>"QLD"),
				"U355"=>array("TOOWOOMBA"=>"QLD"),
				"U357"=>array("CHARTERS TOWERS"=>"QLD"),
				"U360"=>array("GLADSTONE CITY"=>"QLD"),
				"U361"=>array("WEST COURT CA"=>"QLD"),
				"U362"=>array("YEERONGPILLY"=>"QLD"),
				"U364"=>array("STAFFORD"=>"QLD"),
				"U367"=>array("HENDRA"=>"QLD"),
				"U389"=>array("LAWNTON"=>"QLD"),
				"U399"=>array("EMERALD"=>"QLD"),
				"U401"=>array("STURT S%T TOWNSVILLE"=>"QLD"),
				"U402"=>array("GAWLER"=>"SA"),
				"U403"=>array("PENOLA"=>"SA"),
				"U405"=>array("NORWOOD"=>"SA"),
				"U407"=>array("ADELAIDE"=>"SA"),
				"U408"=>array("BROKEN HILL"=>"NSW"),
				"U410"=>array("RICHMOND"=>"SA"),
				"U413"=>array("TANUNDA"=>"SA"),
				"U417"=>array("RENMARK"=>"SA"),
				"U418"=>array("MOBILE DALBY"=>"QLD"),
				"U419"=>array("LOXTON"=>"SA"),
				"U422"=>array("PORT AUGUSTA"=>"SA"),
				"U423"=>array("PORT ADELAIDE"=>"SA"),
				"U426"=>array("MILDURA"=>"VIC"),
				"U428"=>array("PT LINCOLN"=>"SA"),
				"U431"=>array("WINGFIELD"=>"SA"),
				"U438"=>array("MODBURY"=>"SA"),
				"U440"=>array("REYNELLA"=>"SA"),
				"U452"=>array("WHYALLA"=>"SA"),
				"U462"=>array("MURRAY BRIDGE"=>"SA"),
				"U469"=>array("MILLICENT"=>"SA"),
				"U471"=>array("NARACOORTE"=>"SA"),
				"U472"=>array("NOARLUNGA"=>"SA"),
				"U473"=>array("M%T GAMBIER"=>"SA"),
				"U474"=>array("SEAFORD"=>"SA"),
				"U475"=>array("PORT PIRIE"=>"SA"),
				"U478"=>array("VIRGINIA"=>"SA"),
				"U479"=>array("WARRADALE"=>"SA"),
				"U484"=>array("ELIZABETH"=>"SA"),
				"U486"=>array("EDWARDSTOWN"=>"SA"),
				"U493"=>array("ROXBY DOWNS"=>"SA"),
				"U507"=>array("GREGORY HILLS"=>"NSW"),
				"U508"=>array("BALCATTA"=>"WA"),
				"U509"=>array("KEWDALE"=>"WA"),
				"U520"=>array("MIDLAND"=>"WA"),
				"U522"=>array("SPEARWOOD"=>"WA"),
				"U523"=>array("ESPERANCE"=>"WA"),
				"U524"=>array("NORTHAM"=>"WA"),
				"U526"=>array("PORT HEDLAND"=>"WA"),
				"U534"=>array("GERALDTON"=>"WA"),
				"U541"=>array("BUNBURY"=>"WA"),
				"U548"=>array("KWINANA"=>"WA"),
				"U552"=>array("CLAREMONT"=>"WA"),
				"U553"=>array("GERALDTON"=>"WA"),
				"U555"=>array("KARRATHA"=>"WA"),
				"U556"=>array("CANNING VALE"=>"WA"),
				"U559"=>array("ROCKINGHAM"=>"WA"),
				"U561"=>array("BROOME"=>"WA"),
				"U570"=>array("ALBANY"=>"WA"),
				"U572"=>array("EAST VICTORIA PARK"=>"WA"),
				"U580"=>array("KALGOORLIE"=>"WA"),
				"U584"=>array("MANDURAH"=>"WA"),
				"U588"=>array("OSBORNE PARK"=>"WA"),
				"U590"=>array("NARROGIN"=>"WA"),
				"U601"=>array("ERCIAL ORIGIN"=>"VIC"),
				"U603"=>array("WAGIN"=>"WA"),
				"U605"=>array("ANNANDALE"=>"NSW"),
				"U606"=>array("LIVERPOOL"=>"NSW"),
				"U607"=>array("BATHURST"=>"NSW"),
				"U609"=>array("GOULBURN"=>"NSW"),
				"U611"=>array("WETHERILL PARK"=>"NSW"),
				"U612"=>array("PARRAMATTA"=>"NSW"),
				"U614"=>array("QUEANBEYAN"=>"NSW"),
				"U616"=>array("PORT MACQUARIE"=>"NSW"),
				"U620"=>array("KOOLYANOBBING"=>"WA"),
				"U621"=>array("TAMWORTH"=>"NSW"),
				"U623"=>array("INVERELL"=>"NSW"),
				"U627"=>array("DUBBO"=>"NSW"),
				"U630"=>array("STEEL RIVER"=>"NSW"),
				"U643"=>array("GRIFFITH"=>"NSW"),
				"U647"=>array("PARKES"=>"NSW"),
				"U650"=>array("CANBERRA"=>"ACT"),
				"U657"=>array("NARRABRI"=>"NSW"),
				"U670"=>array("WETHERILL PARK%COMMERCIAL"=>"NSW"),
				"U672"=>array("GUNNEDAH"=>"NSW"),
				"U675"=>array("BEGA"=>"NSW"),
				"U676"=>array("ARMIDALE"=>"NSW"),
				"U677"=>array("ST MARYS"=>"NSW"),
				"U679"=>array("GLEN INNES"=>"NSW"),
				"U680"=>array("WOLLONGONG"=>"NSW"),
				"U681"=>array("WAUCHOPE"=>"NSW"),
				"U682"=>array("CAMPBELLTOWN"=>"NSW"),
				"U697"=>array("WYONG"=>"NSW"),
				"U701"=>array("LEONGATHA"=>"VIC"),
				"U705"=>array("MORWELL"=>"VIC"),
				"U706"=>array("SUNBURY"=>"VIC"),
				"U707"=>array("SALE"=>"VIC"),
				"U710"=>array("GEELONG"=>"VIC"),
				"U711"=>array("PRESTON"=>"VIC"),
				"U714"=>array("KNOX"=>"VIC"),
				"U715"=>array("COBDEN"=>"VIC"),
				"U716"=>array("WARRNAMBOOL"=>"VIC"),
				"U718"=>array("NHILL"=>"VIC"),
				"U719"=>array("WESTERN HUB"=>"VIC"),
				"U721"=>array("MULGRAVE"=>"VIC"),
				"U726"=>array("KINGSTON"=>"TAS"),
				"U727"=>array("RINGWOOD"=>"VIC"),
				"U732"=>array("BALLARAT%COMMERCIAL"=>"VIC"),
				"U733"=>array("RICHMOND"=>"VIC"),
				"U734"=>array("BENDIGO"=>"VIC"),
				"U735"=>array("BROOKLYN"=>"VIC"),
				"U736"=>array("ROSANNA"=>"VIC"),
				"U739"=>array("ESSENDON"=>"VIC"),
				"U741"=>array("NEWPORT"=>"VIC"),
				"U742"=>array("WERRIBEE"=>"VIC"),
				"U743"=>array("BENTLEIGH"=>"VIC"),
				"U745"=>array("WEST MELBOURNE"=>"VIC"),
				"U746"=>array("Footscray"=>"VIC"),
				"U748"=>array("CAMPBELLFIELD"=>"VIC"),
				"U751"=>array("WEST FOOTSCRAY"=>"VIC"),
				"U752"=>array("SUNSHINE"=>"VIC"),
				"U754"=>array("BURWOOD"=>"VIC"),
				"U755"=>array("BELLERIVE"=>"TAS"),
				"U756"=>array("BELMONT"=>"VIC"),
				"U757"=>array("BOX HILL"=>"VIC"),
				"U763"=>array("BALLARAT RETAIL"=>"VIC"),
				"U766"=>array("FINLEY"=>"NSW"),
				"U767"=>array("ECHUCA"=>"VIC"),
				"U769"=>array("KEYSBOROUGH"=>"VIC"),
				"U773"=>array("SHEPPARTON"=>"VIC"),
				"U774"=>array("WANGARATTA"=>"VIC"),
				"U776"=>array("COROWA"=>"NSW"),
				"U784"=>array("LAUNCESTON"=>"TAS"),
				"U786"=>array("DELORAINE"=>"TAS"),
				"U794"=>array("CARNARVON"=>"WA"),
				"U796"=>array("WEST KALGOORLIE"=>"WA"),
				"U801"=>array("CHERMSIDE"=>"QLD"),
				"U802"=>array("SOUTH STREET"=>"QLD"),
				"U804"=>array("MURWILLUMBAH"=>"NSW"),
				"U805"=>array("LYTTON"=>"QLD"),
				"U806"=>array("VIRGINIA"=>"QLD"),
				"U807"=>array("INDOOROOPILLY"=>"QLD"),
				"U808"=>array("DALBY"=>"QLD"),
				"U809"=>array("WEST BURLEIGH"=>"QLD"),
				"U812"=>array("THE WILLOWS"=>"QLD"),
				"U813"=>array("ROCKLEA%COMMERCIAL"=>"QLD"),
				"U814"=>array("CASINO"=>"NSW"),
				"U817"=>array("MOUNT ISA"=>"QLD"),
				"U818"=>array(" TYRES STUART"=>"NT"),
				"U819"=>array("DARWIN"=>"NT"),
				"U820"=>array("AYR"=>"QLD"),
				"U821"=>array("KATHERINE"=>"NT"),
				"U823"=>array("BUNDABERG"=>"QLD"),
				"U825"=>array("CAIRNS"=>"QLD"),
				"U826"=>array("ATHERTON"=>"QLD"),
				"U828"=>array("GLADSTONE%COMMERCIAL"=>"QLD"),
				"U830"=>array("GYMPIE"=>"QLD"),
				"U832"=>array("LISMORE"=>"NSW"),
				"U835"=>array("GORDON STREET"=>"QLD"),
				"U836"=>array("NTH IPSWICH"=>"QLD"),
				"U837"=>array("MAREEBA"=>"QLD"),
				"U840"=>array("MACKAY%COMMERCIAL"=>"QLD"),
				"U841"=>array("NAMBOUR"=>"QLD"),
				"U842"=>array("PORTSMITH"=>"QLD"),
				"U843"=>array("ROCKHAMPTON"=>"QLD"),
				"U844"=>array("WINNELLIE"=>"NT"),
				"U846"=>array("MARYBOROUGH"=>"QLD"),
				"U847"=>array("TOOWOOMBA"=>"QLD"),
				"U848"=>array("ASHMORE"=>"QLD"),
				"U854"=>array("GARBUTT"=>"QLD"),
				"U855"=>array("PALMERSTON"=>"NT"),
				"U857"=>array("MORAYFIELD"=>"QLD"),
				"U858"=>array("MACKAY EARTHMOVER"=>"QLD"),
				"U859"=>array("SUNNYBANK"=>"QLD"),
				"U860"=>array("BEENLEIGH"=>"QLD"),
				"U861"=>array("GATTON"=>"QLD"),
				"U864"=>array("MAROOCHYDORE"=>"QLD"),
				"U867"=>array("SOUTHPORT"=>"QLD"),
				"U869"=>array("Chadstone"=>"VIC"),
				"U872"=>array("UNDERWOOD"=>"QLD"),
				"U873"=>array("WARWICK"=>"QLD"),
				"U875"=>array("ALICE SPRINGS"=>"NT"),
				"U877"=>array("MOUNT GRAVATT"=>"QLD"),
				"U879"=>array("CURRIMUNDI"=>"QLD"),
				"U881"=>array("NERANG"=>"QLD")
		);
		
		$counter = 0;
		foreach ($data as $code => $details){
		
			foreach($details as $branch=>$area)
			{
				$stores = Mage::getModel('storelocator/stores')->getCollection()
				->addFieldToSelect('entity_id')
                ->addFieldToFilter('costar_store_code', '')    
				->addFieldToFilter('region', array($area))
				->addFieldToFilter('title', array(
						array('like' => "%$branch%")
				)
				)
				->getFirstItem();
		
				if($stores->getId()){
					$resource = Mage::getSingleton('core/resource');
					$writeConnection = $resource->getConnection('core_write');
					$table = $resource->getTableName('storelocator/stores');
					$id = $stores->getId();
					$costarCode = $code;
		
					$query = "UPDATE {$table} SET costar_store_code = '{$costarCode}' WHERE entity_id = "
					. (int)$id;
					$writeConnection->query($query);
				}else{
					$counter++;
					Mage::log($counter .'-'.$code . '-' .$branch . '-' . $area . '- Store not found.', null, 'costar_store_code.log');
				}
			}
		
		}
	}
}
