<?php
/**
 * Studioforty9_Recaptcha
 *
 * @category  Studioforty9
 * @package   Studioforty9_Recaptcha
 * @author    StudioForty9 <info@studioforty9.com>
 * @copyright 2015 StudioForty9 (http://www.studioforty9.com)
 * @license   https://github.com/studioforty9/recaptcha/blob/master/LICENCE BSD
 * @version   1.2.0
 * @link      https://github.com/studioforty9/recaptcha
 * @see       Studioforty9_Recaptcha_Block_Explicit
 */
?>
<?php if ($this->isAllowed($this->getRequest()->getRouteName())): ?>
<div id="recaptcha-wrapper" data-captcha-sitekey="<?php echo $this->getSiteKey(); ?>" data-captcha-theme="<?php echo $this->getTheme(); ?>">
    <input type="checkbox" id="recaptcha-verification" name="recaptcha-verification" value="" required />
    <div id="recaptcha"></div>
    <small class="error">This is a required field</small>
  
    <script type="text/javascript"> 
        var $recaptchaVerification = jQuery('#recaptcha-verification'),
            $recaptcha = jQuery('#recaptcha-wrapper'),
            siteKey = $recaptcha.data('captcha-sitekey'),
            theme = $recaptcha.data('captcha-theme');
        
        // Init recaptcha and add foundation field requered
        var onloadCallback = function() {
            var verifyCallback = function(response) {
                if (response.success = true) {
                   $recaptchaVerification.click();
                } else {
                    if ($recaptchaVerification.is(':checked')) {
                        $recaptchaVerification.prop('checked', false);
                    }
                }
            };
            grecaptcha.render('recaptcha', {
                'sitekey': siteKey,
                'theme': theme,
                'callback': verifyCallback
            });
        };
    </script>
  
    <?php echo $this->getRecaptchaScript(); ?>
</div>
<?php endif; ?>
