<?php
    $store_Id = Mage::app()->getStore()->getId();
    $type = $this->getRequest()->getParam('faqType');
    $categories = $this->getAllCategory();
    $page_size = Mage::getStoreConfig('faq/general/page_size_number',$store_Id);
    $id = $this->getRequest()->getParam('id');
?>

<div class="ms-faq">
  <h1 class="page-title"><?php echo($this->__("FAQ Topics"));?></h1>

  <div id="faq-container"<?php if($this->getRequest()->getParam('id')): ?>class="active"<?php endif;?>>
    <div class="row">

      <div class="columns medium-4 large-3">
        <section>
          <input type="text" name="keyword" id="keyword"placeholder="<?php echo $this->__('Search FAQ') ?>" class="form-control input-text required-entry" size="30" maxlength="150" />
          <button type="button" onclick="ajaxSearch()" class="btnSearch radius button expand" title="<?php echo $this->__('Search FAQ');?>"><?php echo $this->__('Search');?></button>
        </section>
        <hr>
        <section class="my-account">
          <h4>Categories</h4>
          <ul class="form-group no-bullet side-nav">
              <li onclick="moveright(this)">
                <a title="<?php echo $this->__('Most FAQs');?>" onclick="loadfaq(this,'most',null,1)" class="faq-link faq-navigator first<?php if(!$id&&($type=='most'|| $type== null)): ?> active<?php endif;?>"><?php echo $this->__("Most FAQs")  ?></a>
              </li>
              <?php $i=1; foreach($categories as $category):?>
              <li onclick="moveright(this)">
                <a title="<?php echo $this->stripTags($category->getName());?>" onclick="loadfaq(this,'category',<?php echo $category->getId();?>,1)" class="faq-link faq-navigator <?php if($i>=count($categories)):?> last<?php endif; ?>"><?php echo $this->stripTags($category->getName());  ?></a>
              </li>
              <?php $i++; endforeach;?>
          </ul>
        </section>

      </div>
      <div class="columns medium-8 large-9">

        <div class="faq-main" id="faq-main">
            <a onclick="moveback()" id="title-back" class="form-group text-center hide"><?php if($this->getRequest()->getParam('id')) echo $this->__("Back");?></a>
            <div class="form-group" id="faq_listing">
                <?php echo $this->getChildHtml('faq.listing'); ?>
            </div>
            <div class="faq-fade" id="faq-fade" style="display: none;">
              <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
              <span class="sr-only">Loading...</span>
            </div>
            <input type="hidden" value='most' id="faqtype" name="type"/>
            <input type="hidden" value='' id="faqid" name="categoryId"/>
        </div>

      </div>
    </div>

  </div>

</div>

<script type="text/javascript">
    function loadfaq(el,type,category_id,page){
        $('faqtype').value= type;
        $('faqid').value = category_id;
        if(!el.hasClassName('active')){
            var url = '<?php echo $this->getUrl('faq/index/ajaxview') ?>';
            var param = {faqType: type, faqId: category_id,page:page};
            var link = $$('.faq-link');
            link.each(function(link){
                link.removeClassName('active');
            });
            el.addClassName('active');
            $('faq-fade').show();
            new Ajax.Request(url, {
                method:'get',
                parameters:param,
                onComplete: function(transport) {
                  document.getElementById("faq_listing").innerHTML = transport.responseText.evalJSON();
                  $('faq-fade').hide();
                }
              });
        }
    }
    function ajaxSearch(){
        if(!$('keyword').value.trim()){
            $('faq-validation').show();
            $('keyword').addClassName('validation-failed');
        }else{
            moveright(null);
            var url = '<?php echo $this->getUrl('faq/index/ajaxview') ?>';
            var param = {faqType: 'search', faqId: $('keyword').value,page:1};
            $('faq-fade').show();
            new Ajax.Request(url, {
                method: 'get',
                parameters:param,
                onComplete: function(transport){
                    console.log('transport', transport);

                    // $('faq-validation').hide();
                    //  $('keyword').removeClassName('validation-failed');
                    $('faq-fade').hide();
                    console.log('done', $('faq-fade'));

                    document.getElementById("faq_listing").innerHTML = transport.responseText.evalJSON();
                    var link = $$('.faq-link');
                    link.each(function(link){
                        link.removeClassName('active');
                    });
                },
            });
        }
	return false;
    }
    function loadpage(el,type,category_id,page){
        if(!el.hasClassName('active')){
            var url = '<?php echo $this->getUrl('faq/index/ajaxview') ?>';
            var param = {faqType: type, faqId: category_id,page:page};
            var link = $$('.faq-page');
            $('faq-fade').show();
            new Ajax.Request(url, {
                method:'get',
                parameters:param,
                onComplete: function(transport) {
                  document.getElementById("faq_listing").innerHTML = transport.responseText.evalJSON();
                  $('faq-fade').hide();
                }
              });
            if(screen.width < 768)
              window.scroll(0,$('faq-container').cumulativeOffset().top)
        }
    }
    function faqOpen(el){
        if($('faq-question-'+el).hasClassName('active')){
            $('faq-question-'+el).removeClassName('active');
        }else{
            $('faq-question-'+el).addClassName('active');
        }
        Effect.toggle('faq-content-'+el, 'blind', { duration: 0.1 });
     }
     $('keyword').observe('keypress', submitSearch);
     function submitSearch(event){
         if(event.keyCode == 13){
             ajaxSearch();
         }
     }
     function moveright(el){
         if(el == null){
            var title = 'Search results';
            var $html = '<span class="glyphicon small glyphicon-chevron-left">&nbsp;</span>'+title;
            document.getElementById("title-back").innerHTML = $html;
            $('faq-container').addClassName('active');
         }else{
            if(el.readAttribute('title'))
                var title = el.readAttribute('title');
            else
               var title = el.down('a').readAttribute('title');
            var $html = '<span class="glyphicon small glyphicon-chevron-left">&nbsp;</span>'+title;
            document.getElementById("title-back").innerHTML = $html;
            $('faq-container').addClassName('active');
         }
     }
     function moveback(){
         $('faq-container').removeClassName('active');
     }
     window.onresize = function(){
         if(screen.width > 767) moveback();
     }
</script>
