<section id="product-filter-panel" class="disabled">    
    <div class="filter with-caret-arrow" data-filter-accordion-nav>
        <i class="fa fa-filter"></i> Filter
    </div>

    <div class="filter-content" data-filter-accordion-content>
        <div class="categories">
            <div class="category">
                <div class="category-title with-caret-arrow">
                    Price
                </div>
                <div class="category-content active">
                    <ul>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <span>$0 - $99.99 (2)</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <span>$100 - $199.99 (7)</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox" checked>
                                <span>$100 - $199.99 (7)</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <span>$300 and above</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="category">
                <div class="category-title with-caret-arrow">
                    Features
                </div>
                <div class="category-content">
                    <ul>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <i class="icon2 icon-breaking-performance"></i>
                                <span>Braking Performace (14)</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <i class="icon2 icon-comfort-performance"></i>
                                <span>Comfort Performace (2)</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <i class="icon2 icon-fuel-economy"></i>
                                <span>Fuel Economy(15)</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <i class="icon2 icon-grip-performance"></i>
                                <span>Grip Performace (3)</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <i class="icon2 icon-value-tyre"></i>
                                <span>Value (9)</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="category">
                <div class="category-title with-caret-arrow">
                    Types
                </div>
                <div class="category-content">
                    <ul>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <span>Passenger</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <span>4WD</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="category">
                <div class="category-title with-caret-arrow">
                    Brands
                </div>
                <div class="category-content">
                    <ul>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <span>Dunlop (22)</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <span>Goodyear (1)</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <span>Goodyear</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <span>Pirelli (4)</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="custom-field checkbox reverse">
                                <input type="checkbox">
                                <span>Quality Steel Radial</span>
                                <div class="indicator"></div>
                            </label>
                        </li>
                    </ul>
                </div>
            </div>
        </div>	
        <div class="cta-container">
            <button type="submit" class="flat-button secondary" disabled>Apply Filter</button>
        </div>
    </div>
</section>