<?php // this is not used anymore ?>
<?php // echo $this->getChildHtml('review_form') ?>


<?php /*



<div class="box-collateral box-reviews" id="customer-reviews">
        

		<div class="polar-toggle form-add">
                    
                    <?php // echo $this->getChildHtml('review_form') // TODO: use this and layout XML rather than hardcoding ?>
                                      
		<h2>Write Your Own Review</h2>
        <form action="/review/product/post/id/<?php echo Mage::registry('current_product')->getId();?>/" method="post" id="review-form">
            
        <fieldset>
            
                <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
            
                <h4>How do you rate this product? <em class="required">*</em></h4>
                <span id="input-message-box"></span>
                <ul class="rating-list">
<!--                <li class="value">
                        <span>Price:</span>
							<select name="ratings[3]">
								<option value="11">1 stars</option>
								<option value="12">2 stars</option>
								<option value="13">3 stars</option>
								<option value="14">4 stars</option>
								<option value="15">5 stars</option>
							</select>
                    </li>
                    <li class="value">
                        <span>Value:</span>
                        <select name="ratings[2]">
							  <option value="6">1 stars</option>
							  <option value="7">2 stars</option>
							  <option value="8">3 stars</option>
							  <option value="9">4 stars</option>
							  <option value="10">5 stars</option>
                          </select>
                    </li> -->
                    <li class="value">
                        <span>Rating:</span>
                        <select name="ratings[1]">
                        <option value="1">1 stars</option>
                        <option value="2">2 stars</option>
                        <option value="3">3 stars</option>
                        <option value="4">4 stars</option>
                        <option value="5">5 stars</option>
                        </select>
                    </li>
                    </ul>
                <script type="text/javascript">decorateTable('product-review-table')</script>
                <ul class="form-list">
                    <li>
                        <label for="nickname_field" class="required"><em>*</em>Nickname</label>
                        <div class="input-box">
                            <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" value="">
                        </div>
                    </li>
                    <li>
                        <label for="summary_field" class="required"><em>*</em>Summary of Your Review</label>
                        <div class="input-box">
                            <input type="text" name="title" id="summary_field" class="input-text required-entry" value="">
                        </div>
                    </li>
                    <li>
                        <label for="review_field" class="required"><em>*</em>Review</label>
                        <div class="input-box">
                            <textarea name="detail" id="review_field" cols="5" rows="3" class="required-entry"></textarea>
                        </div>
                    </li>
                </ul>
            </fieldset>
            <div class="buttons-set">
                <button type="submit" title="Submit Review" class="button"><span><span>Submit Review</span></span></button>
            </div>
    </form>
    </div>
</div>
  
 */ ?>