<div class="row full-width">
    <div class="columns small-12">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage-promo-1-full-width')->toHtml(); ?>
    </div>
</div>
<div class="row full-width">
    <div class="columns small-12 medium-6">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage-promo-1-left')->toHtml(); ?>
    </div>
    <div class="columns small-12 medium-6">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage-promo-2-right')->toHtml(); ?>
    </div>
</div>