<?php
/**
 * Customer who viewed this item also viewed this
 */

?>
<?php $_helper = Mage::helper('apdinteract_whoalsoview'); ?>
<?php $limit = 5;?>
<?php $_product = $this->getProduct(); ?>
<?php $collection = $_helper->_getCustomersAlsoViewedProducts($_product->getId(),$limit)?>
<?php $storeId = Mage::app()->getStore()->getId();?>
	<?php if ( count($collection) > 0):?>

		<div class="row collapse also-viewed">
			<div class="columns">
					<h3 class="section-title"><?php  echo $this->__('Customers who viewed this item also viewed') ?></h3>

				  <div class="related-product-slider" data-equalizer>
					<?php foreach ($collection as $_item):
						$badge_th_img ="";
						$badge_th = Mage::helper('apdinteract_catalog')->getBadgeSrc($_item->getAttributeText('overlay'), $thumb = true);

						if(isset($badge_th) && $badge_th!='')
							//$badge_th_img = "<img class=\"product-badge\" src=\"".$badge_th."\" alt=\"".$_item->getAttributeText('overlay')."\">";
							$overlay_text = $_item->getAttributeText('overlay');
							$catalogue = str_replace(' ', '', strtolower($overlay_text));
							if (strpos($catalogue, 'new') !== false){
								$catalogue = 'new';
							}
							$badge_th_img = "<div class=\"product-badge-block small {$catalogue}\">{$overlay_text}</div>";

					?>

					<div class="item medium-3 columns">
						<div class="row product-item">
							<div class="small-3 columns">
							  <?php $product = Mage::getModel('catalog/product')->load($_item->getId());?>
							  <?php  $productUrl =  Mage::helper("apdwidgets")->getFullProductUrl($product);?>
							  <?php $cats = reset($product->getCategoryIds());?>
							  <?php $category = Mage::getModel('catalog/category')->load($cats);?>
							  <div class="product-image">
								<a href="<?php echo $productUrl?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(100) ?>" class="expand" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" class="expand"></a>
							  </div>
							</div>
							<div data-equalizer-watch="" class="small-9 columns product-slider-detail">
							  <div class="product-details">
								<?php echo $badge_th_img ?>

								<?php $brand = $this->getSkinUrl('images/brands/' . strtolower($_item->getAttributeText('brand')) . '-logo.png');
								 // $url = getimagesize($brand);
                                                                // This doesn't work with https for some reason
								if (true || is_array($url)) {?>
								 <img src="<?php echo $brand;?>" alt="<?php echo $_item->getAttributeText('brand'); ?>" />
								<?php }?>
								<h5 class="product-title"><a href="<?php echo $productUrl?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h5>
                                <?php $ratings = Mage::getModel('review/review_summary')?>
								<?php $ratings = $ratings->setStoreId($storeId)->load($_item->getId());?>
								<div class="star-rating">
									 <?php
									 if ( !empty($ratings['rating_summary']) ) {
										echo Mage::helper('apdwidgets')->getStarHtmlFromRating($ratings['rating_summary']);
									}
									 ?>
								</div>
                                <?php
									$minimumPriceFromSimple = Mage::helper('apdinteract_catalog')->shouldDisplayMinimalPrice($_item);
									$rrp = Mage::helper('core')->currency($minimumPriceFromSimple['rrp_price']);
									$onlinePrice = Mage::helper('core')->currency($minimumPriceFromSimple['online_price']);
									$from = Mage::helper('apdinteract_catalog')->shouldDisplayFromText($_item);
                                    $isConfigurable = Mage::helper('apdinteract_catalog')->isConfigurable($_item);
                                ?>

								<?php if ($minimumPriceFromSimple['rrp_price'] > $minimumPriceFromSimple['online_price'] && $minimumPriceFromSimple['online_price'] != 0 ):?>
								<div class="price-label">RRP:</div>
								<div class="rrp">
									<span class="rrp-amount"><?php echo $rrp?>/ea</span>
								</div>
								<div class="price-label">Online <?php echo $from?></div>
								<div class="online-price">
									<span class="online-price"><?php echo $onlinePrice?>/ea</span>
								</div>
								<?php elseif (($minimumPriceFromSimple['online_price'] != 0  && ($minimumPriceFromSimple['special_price'] == null || $minimumPriceFromSimple['special_price'] == 0 ))):?>
									<div class="price-label">Online <?php echo $from?></div>
									<div class="online-price">
										<span class="online-price"><?php echo $onlinePrice?>/ea</span>
									</div>
								<?php elseif (($minimumPriceFromSimple['online_price'] >= $minimumPriceFromSimple['rrp_price']) || ($data['online_price'] == 0)):?>
									<div class="price-label">Request price</div>
								<?php endif;?>

								<?php $productCompareHelper = $this->helper('catalog/product_compare');
								  $_compareItems = $productCompareHelper->getItemCount() > 0 ? $productCompareHelper->getItemCollection() : array();
								  $compareProductIds = array();
								  foreach ($_compareItems as $item) {
									  $compareProductIds[] = $item->getId();
								  }
								?>

								<?php //if ($_compareItems && (in_array($_item->getId(), $compareProductIds))): ?>
									<!--<a href="javascript:;" class="link-compare"  onclick="popWin('<?php //echo $productCompareHelper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><?php //echo $this->__('View Compare')?></a>
								<?php //elseif($_compareUrl = $this->getAddToCompareUrl($_item)):?>
									<a href="<?php //echo $_compareUrl?>" class="link-compare"><?php //echo $this->__('Add to Compare')?></a>-->
								<?php //endif; ?>
							  </div>

							</div>

						</div>
					</div>

            <?php endforeach;?>
          </div>
	  </div>
    </div>
	<?php endif;?>
