<?php
require_once(__DIR__.'/../../../../../../../app/Mage.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-03 at 10:12:22.
 */
class ApdInteract_SilverpopApi_Helper_DataTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ApdInteract_SilverpopApi_Helper_Data
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        Mage::app();
        
        $this->lists = array(
            'Beaurepaires - Marketing - General Newsletter',
            'Beaurepaires - Marketing - Special Offers and Rewards',
            'Beaurepaires - Marketing - Product News',
            );

        $this->email = 'silaspalmer+test123@gmail.com';
        
        
        $this->object = Mage::helper('silverpopapi');        
        $this->object->silverpopLogin();
        
        // Create the mailing lists if they don't already exist
        // $result = $this->object->createContactLists($this->lists);  
        // fwrite(STDOUT, print_r($result, true) . "\n");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object->silverpopLogout();
    }

    /**
     * @covers ApdInteract_SilverpopApi_Helper_Data::silverpopLogin
     * 
     * @covers ApdInteract_SilverpopApi_Helper_Data::_xmlToSilverpop
     * @covers ApdInteract_SilverpopApi_Helper_Data::_loadXml
     * @covers ApdInteract_SilverpopApi_Helper_Data::_logException
     * @covers ApdInteract_SilverpopApi_Helper_Data::_jsessionidFromLoginResponse
     * @covers ApdInteract_SilverpopApi_Helper_Data::_getConfigValue
     * @covers ApdInteract_SilverpopApi_Helper_Data::_getUsername
     * @covers ApdInteract_SilverpopApi_Helper_Data::_getPassword
     * @covers ApdInteract_SilverpopApi_Helper_Data::_getDatabaseName
     * 
     * @covers ApdInteract_SilverpopApi_Helper_Data::silverpopLogout
     * @covers ApdInteract_SilverpopApi_Helper_Data::getLists
     */
    public function testGetLists()
    {
        $result = $this->object->getLists();
        fwrite(STDOUT, print_r($result, true) . "\n"); // Dumps result to the output window. Useful for debugging
        $this->assertTrue(isset($result->Body->RESULT->LIST));
    }
    
    /**
     * @covers ApdInteract_SilverpopApi_Helper_Data::addContactToLists
     */
    public function testAddContactToLists()
    {
        $result = $this->object->addContactToLists($this->email, $this->lists);
        fwrite(STDOUT, print_r($result, true) . "\n"); // Dumps result to the output window. Useful for debugging
        $this->assertTrue($result->Body->RESULT->SUCCESS == 'TRUE');
    }
    
    /**
     * @covers ApdInteract_SilverpopApi_Helper_Data::removeContactFromLists
     */
    public function testRemoveContactFromLists()
    {
        $result = $this->object->removeContactFromLists($this->email, $this->lists);
        fwrite(STDOUT, print_r($result, true) . "\n"); // Dumps result to the output window. Useful for debugging
        $this->assertTrue($result[0]->Body->RESULT->SUCCESS == 'TRUE');
    }
    
}