<!-- Promo Bar -->
<?php
    // System Configuration > Promo > Promo Messages
    $messages = array();
    $messages[1] = Mage::getStoreConfig('badges/promo_message/message_1');
    $link[1]    = Mage::getStoreConfig('badges/promo_message/link_1');
    $messages[2] = Mage::getStoreConfig('badges/promo_message/message_2');
    $link[2]    = Mage::getStoreConfig('badges/promo_message/link_2');

    $arr_message = array_filter($messages);
?>
<div class="promo-bar hide-for-small">
    <div class="row full-width">
        <div class="small-12 medium-5 columns">
            <?php if(count($arr_message) > 0){ ?>
            <i class="fa fa-play"></i>
            <ul class="promo-messages promo-bar-msgs">
                <?php foreach($arr_message as $key => $message){
                    if($link[$key] != ''){
                        echo "<li><a href='".$link[$key]."'>" . $message . "</a></li>";
                    }else{
                        echo "<li>" . $message . "</li>";
                    }
                } ?>
            </ul>
            <?php } ?>
        </div>
        <div class="medium-7 hide-for-small-only text-right columns">
          <!--
          <div class="header-newletter">
            <div class="row">
              <div class="medium-4 columns">
                <label for="header-newsletter-input">Offers and News</label>
              </div>
              <div class="medium-8 columns">
                <form action="/subscribe/index/newsletter/" method="post" class="newsletter" novalidate>
                    <div class="row collapse newsletter-field">
                      <div class="small-10 columns">
                        <input type="email" placeholder="Email address" class="field" name="email" id="header-newsletter-input" title="Email Address" required>
                        <p class="result"></p>
                      </div>
                      <div class="small-2 columns">
                          <button type="submit" class="button secondary"><i class="fa fa-envelope"></i></button>
                      </div>
                    </div>
                 </form>
               </div>
            </div>
          -->
          <form action="/subscribe/index/newsletter/" method="post" class="newsletter" novalidate>
          <ul class="inline-list header-newletter right">
            <li>
              <label for="header-newsletter-input">Offers and News</label>
            </li>
            <li>
              <input type="header-newsletter-input" placeholder="Email address" class="field" name="email" id="email" title="Email Address" required>
              <div class="result"></div>
            </li>
            <li>
              <button type="submit" class="button secondary"><i class="fa fa-envelope"></i></button>
            </li>
          </ul>
          </form>
          </div>

        </div>
    </div>
</div>
<!-- End Promo Bar -->
