<?php
    /**
    * Copyright © Pulsestorm LLC: All rights reserved
    */

//die('installing');

    $installer = $this;
    $installer->startSetup();
    
    
//    try
//	{
        $installer->run("
        DROP TABLE IF EXISTS `{$installer->getTable('apdinteract_vir/order')}`;    
        CREATE TABLE `{$installer->getTable('apdinteract_vir/order')}` (
        `parent_id` int(11) NOT NULL AUTO_INCREMENT,
        `orderdate` DATE NULL DEFAULT NULL,
        `timereq` TIME NULL DEFAULT NULL,
        `invoiceno` VARCHAR( 10 ) NULL DEFAULT NULL,
        `vir_type` int(11) NOT NULL,
        `lastbalance` tinyint(4) DEFAULT NULL COMMENT '0 = 0-6 months, 1 = 6-12 months, 2 = over 12 months',
        `lastwheelalignment` tinyint(4) DEFAULT NULL COMMENT '0 = 0-6 months, 1 = 6-12 months, 2 = over 12 months',
        `vehiclemake` varchar(255) DEFAULT NULL,
        `vehicleyear` varchar(10) DEFAULT NULL,
        `vehiclemodel` varchar(255) DEFAULT NULL,
        `vehiclerego` varchar(255) DEFAULT NULL,
        `vehicleodometer` varchar(255) DEFAULT NULL,
        `vehiclecomments` text,
        `vehiclecommentsimage` varchar(1000) DEFAULT NULL,
        `vehiclewheelLF` tinyint(1) DEFAULT NULL,
        `vehiclewheelLFtorque` varchar(255) DEFAULT NULL,
        `vehiclewheelRF` tinyint(1) DEFAULT NULL,
        `vehiclewheelRFtorque` varchar(255) DEFAULT NULL,
        `vehiclewheelLR` tinyint(1) DEFAULT NULL,
        `vehiclewheelLRtorque` varchar(255) DEFAULT NULL,
        `vehiclewheelRR` tinyint(1) DEFAULT NULL,
        `vehiclewheelRRtorque` varchar(255) DEFAULT NULL,
        `vehiclewheelSPARE` tinyint(1) DEFAULT NULL,
        `vehiclewheelSPAREtorque` varchar(255) DEFAULT NULL,
        `spareconditioncomment` varchar(255) DEFAULT NULL,
        `workordertyresdescription` varchar(255) DEFAULT NULL, 
        `workordertyresqty` int(11) DEFAULT NULL,
        `workordertyresprice` decimal(10,3) DEFAULT NULL,
        `workorderbalancesoptionsteel` tinyint(1) DEFAULT NULL,
        `workorderbalancesoptionalloy` tinyint(1) DEFAULT NULL,
        `workorderbalancesoptionpremium` tinyint(1) DEFAULT NULL,
        `workorderbalancesqty` int(11) DEFAULT NULL,
        `workorderbalancesprice` decimal(10,3) DEFAULT NULL,
        `workorderalignoptionstandard` tinyint(1) DEFAULT NULL,
        `workorderalignoptionthrust` tinyint(1) DEFAULT NULL,
        `workorderalignoption4wheel` tinyint(1) DEFAULT NULL,
        `workorderalignoption4wd` tinyint(1) DEFAULT NULL,
        `workorderalignqty` int(11) DEFAULT NULL,
        `workorderalignprice` decimal(10,3) DEFAULT NULL,
        `workorderwheelsqty` int(11) DEFAULT NULL,
        `workorderwheelsprice` decimal(10,3) DEFAULT NULL,
        `workorderwheelsdescription` varchar(255) DEFAULT NULL,
        `workorderbatreportdescription` varchar(255) DEFAULT NULL,
        `workorderbatreportqty` int(11) DEFAULT NULL,
        `workorderbatreportprice` decimal(10,0) DEFAULT NULL,
        `workorderbrakesdescription` varchar(255) DEFAULT NULL,
        `workorderbrakesqty` int(11) DEFAULT NULL,
        `workorderbrakesprice` decimal(10,3) DEFAULT NULL,
        `workorderotherdescription` varchar(255) DEFAULT NULL,
        `workorderotherqty` int(11) DEFAULT NULL,
        `workorderotherprice` decimal(10,3) DEFAULT NULL,
        `workorderpuncturedescription` varchar(255) DEFAULT NULL, 
        `workorderpunctureqty` int(11) DEFAULT NULL,
        `workorderpunctureprice` decimal(10,3) DEFAULT NULL,
        `custapprpaycash` int(11) DEFAULT NULL,
        `custapprpayvisamaster` int(11) DEFAULT NULL,
        `custapprpayaccount` int(11) DEFAULT NULL,
        `custapprpayother` int(11) DEFAULT NULL,
        `custapprpayeftpos` int(11) DEFAULT NULL,
        `custapprpayamexdiners` int(11) DEFAULT NULL,
        `custapprpayfinance` int(11) DEFAULT NULL,
        `custapprsignatureimage` LONGTEXT DEFAULT NULL,
        `custapprsubscribe` int(11) DEFAULT NULL,
        `custapprcollectdata` int(11) DEFAULT NULL,
        `custapprcall` tinyint(1) DEFAULT NULL,
        `workshopsignatureimage` LONGTEXT DEFAULT NULL,
        `wheelalignfrontbeforeleftcamber` varchar(10) DEFAULT NULL,
        `wheelalignfrontbeforeleftcamber2` varchar(10) DEFAULT NULL,
        `wheelalignfrontbeforeleftcaster` varchar(10) DEFAULT NULL,
        `wheelalignfrontbeforeleftcaster2` varchar(10) DEFAULT NULL,
        `wheelalignfrontbeforelefttoein` varchar(10) DEFAULT NULL,
        `wheelalignfrontbeforelefttoein2` varchar(10) DEFAULT NULL,
        `wheelalignfrontbeforerightcamber` varchar(10) DEFAULT NULL,
        `wheelalignfrontbeforerightcamber2` varchar(10) DEFAULT NULL,
        `wheelalignfrontbeforerightcaster` varchar(10) DEFAULT NULL,
        `wheelalignfrontbeforerightcaster2` varchar(10) DEFAULT NULL,
        `wheelalignfrontbeforerighttoein` varchar(10) DEFAULT NULL,
        `wheelalignfrontbeforerighttoein2` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterleftcamber` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterleftcamber2` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterleftcaster` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterleftcaster2` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterlefttoein` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterlefttoein2` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterrightcamber` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterrightcamber2` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterrightcaster` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterrightcaster2` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterrighttoein` varchar(10) DEFAULT NULL,
        `wheelalignfrontafterrighttoein2` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforeleftcamber` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforeleftcamber2` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforeleftcaster` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforeleftcaster2` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforelefttoein` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforelefttoein2` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforerightcamber` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforerightcamber2` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforerightcaster` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforerightcaster2` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforerighttoein` varchar(10) DEFAULT NULL,
        `wheelalignrearbeforerighttoein2` varchar(10) DEFAULT NULL,
        `wheelalignrearafterleftcamber` varchar(10) DEFAULT NULL,
        `wheelalignrearafterleftcamber2` varchar(10) DEFAULT NULL,
        `wheelalignrearafterleftcaster` varchar(10) DEFAULT NULL,
        `wheelalignrearafterleftcaster2` varchar(10) DEFAULT NULL,
        `wheelalignrearafterlefttoein` varchar(10) DEFAULT NULL,
        `wheelalignrearafterlefttoein2` varchar(10) DEFAULT NULL,
        `wheelalignrearafterrightcamber` varchar(10) DEFAULT NULL,
        `wheelalignrearafterrightcamber2` varchar(10) DEFAULT NULL,
        `wheelalignrearafterrightcaster` varchar(10) DEFAULT NULL,
        `wheelalignrearafterrightcaster2` varchar(10) DEFAULT NULL,
        `wheelalignrearafterrighttoein` varchar(10) DEFAULT NULL,
        `wheelalignrearafterrighttoein2` varchar(10) DEFAULT NULL,
        `wheelalignchecksteerwheelstraight` int(11) DEFAULT NULL,
        `wheelalignchecksteerwheelstraightvalue` varchar(100) DEFAULT NULL,
        `wheelaligncheckwehicleroadtested` int(11) DEFAULT NULL,
        `wheelaligncheckwehicleroadtestedvalue` varchar(100) DEFAULT NULL,
        `wheelaligncheckcovermatremoved` int(11) DEFAULT NULL,
        `wheelaligncheckcovermatremovedvalue` varchar(100) DEFAULT NULL,
        `wheelaligncheckstickerinstalled` int(11) DEFAULT NULL,
        `wheelaligncheckstickerinstalledvalue` varchar(100) DEFAULT NULL,
        `wheelaligncheckcompletedby` varchar(255) DEFAULT NULL,
        `tyrecheckwheelnutstorqued` int(11) DEFAULT NULL,
        `tyrecheckwheelnutstorquedvalue` varchar(100) DEFAULT NULL,
        `tyrecheckmetalvalvecapsfitted` int(11) DEFAULT NULL,
        `tyrecheckmetalvalvecapsfittedvalue` varchar(100) DEFAULT NULL,
        `tyrechecktyresglosssed` int(11) DEFAULT NULL,
        `tyrechecktyresglosssedvalue` varchar(100) DEFAULT NULL,
        `tyrecheckbatterystickerfitted` int(11) DEFAULT NULL,
        `tyrecheckbatterystickerfittedvalue` varchar(100) DEFAULT NULL,
        `tyrechecksparetyrestickerfitted` int(11) DEFAULT NULL,
        `tyrechecksparetyrestickerfittedvalue` varchar(100) DEFAULT NULL,
        `tyrecheckcompletedby` varchar(255) DEFAULT NULL,
        `batterychecktestresult` varchar(255) DEFAULT NULL,
        `batterycheckterminals` varchar(255) DEFAULT NULL,
        `visualbrakefrontcallipers` varchar(255) DEFAULT NULL,
        `visualbrakefrontbrakes` varchar(255) DEFAULT NULL,
        `visualbrakefrontdiscs` varchar(255) DEFAULT NULL,
        `visualbrakerearcallipers` varchar(255) DEFAULT NULL,
        `visualbrakerearbrakes` varchar(255) DEFAULT NULL,
        `visualbrakereardiscs` varchar(255) DEFAULT NULL,
        `visualbrakerearflexiblehoses` varchar(255) DEFAULT NULL,
        `created_at` datetime NULL DEFAULT NULL,
        `updated_at` datetime NULL DEFAULT NULL,
        `custname` VARCHAR (255) NULL,
        `custaddress` VARCHAR (255) NULL,        
        `custsuburb` VARCHAR(100) NULL,
        `custstate` VARCHAR(20) DEFAULT NULL,
        `custpostcode` VARCHAR(10) NULL,
        `custphoneno` VARCHAR(25) NULL,
        `custphonemobile` VARCHAR(25) NULL,
        `custemail` VARCHAR(255) NULL,
        PRIMARY KEY (`parent_id`)
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
        
        DROP TABLE IF EXISTS `{$installer->getTable('apdinteract_vir/ordercommercial')}`;    
        CREATE TABLE `{$installer->getTable('apdinteract_vir/ordercommercial')}` (
        `parent_id` int(11) NOT NULL AUTO_INCREMENT,
        `vir_type` int(11) NOT NULL,
        `inspectiondate` date DEFAULT NULL,
        `Invoicenumber` int(11) DEFAULT NULL,
        `baynumber` int(11) DEFAULT NULL,
        `ordernumber` int(11) DEFAULT NULL,
        `paymenttype` varchar(25) DEFAULT NULL,
        `customername` varchar(255) DEFAULT NULL,
        `phonenumber` varchar(25) DEFAULT NULL,
        `phonemobile` varchar(25) DEFAULT NULL,
        `addressline1` varchar(255) DEFAULT NULL,
        `addressline2` varchar(255) DEFAULT NULL,
        `suburb` varchar(255) DEFAULT NULL,
        `state` varchar(20) DEFAULT NULL,
        `postcode` varchar(10) DEFAULT NULL,
        `regonumber` varchar(25) DEFAULT NULL,
        `fleetnumber` varchar(25) DEFAULT NULL,
        `speedohubreading` varchar(25) DEFAULT NULL,
        `wheelp1` tinyint(1) DEFAULT 0,
        `wheelp2` tinyint(1) DEFAULT 0,
        `wheelp1a` tinyint(1) DEFAULT 0,
        `wheelp2a` tinyint(1) DEFAULT 0,
        `wheelp3` tinyint(1) DEFAULT 0,
        `wheelp4` tinyint(1) DEFAULT 0,
        `wheelp5` tinyint(1) DEFAULT 0,
        `wheelp6` tinyint(1) DEFAULT 0,
        `wheelp7` tinyint(1) DEFAULT 0,
        `wheelp8` tinyint(1) DEFAULT 0,
        `wheelp9` tinyint(1) DEFAULT 0,
        `wheelp10` tinyint(1) DEFAULT 0,
        `wheela1` tinyint(1) DEFAULT 0,
        `wheela2` tinyint(1) DEFAULT 0,
        `wheela3` tinyint(1) DEFAULT 0,
        `wheela4` tinyint(1) DEFAULT 0,
        `wheela5` tinyint(1) DEFAULT 0,
        `wheela6` tinyint(1) DEFAULT 0,
        `wheela7` tinyint(1) DEFAULT 0,
        `wheela8` tinyint(1) DEFAULT 0,
        `wheela9` tinyint(1) DEFAULT 0,
        `wheela10` tinyint(1) DEFAULT 0,
        `wheela11` tinyint(1) DEFAULT 0,
        `wheela12` tinyint(1) DEFAULT 0,
        `wheelb1` tinyint(1) DEFAULT 0,
        `wheelb2` tinyint(1) DEFAULT 0,
        `wheelb3` tinyint(1) DEFAULT 0,
        `wheelb4` tinyint(1) DEFAULT 0,
        `wheelb5` tinyint(1) DEFAULT 0,
        `wheelb6` tinyint(1) DEFAULT 0,
        `wheelb7` tinyint(1) DEFAULT 0,
        `wheelb8` tinyint(1) DEFAULT 0,
        `wheelb9` tinyint(1) DEFAULT 0,
        `wheelb10` tinyint(1) DEFAULT 0,
        `wheelb11` tinyint(1) DEFAULT 0,
        `wheelb12` tinyint(1) DEFAULT 0,
        `vehicledrawingimage` varchar(1000) DEFAULT NULL,
        `workrequireddone` varchar(255) DEFAULT NULL,
        `newsteersize` varchar(255) DEFAULT NULL,
        `newsteerpattern` varchar(255) DEFAULT NULL,
        `newsteerqty` int(11) DEFAULT NULL,
        `newsteercomments` varchar(255) DEFAULT NULL,
        `newdrivesize` varchar(255) DEFAULT NULL,
        `newdrivepattern` varchar(255) DEFAULT NULL,
        `newdriveqty` int(11) DEFAULT NULL,
        `newdrivecomments` varchar(255) DEFAULT NULL,
        `newtrailersize` varchar(255) DEFAULT NULL,
        `newtrailerpattern` varchar(255) DEFAULT NULL,
        `newtrailerqty` int(11) DEFAULT NULL,
        `newtrailercomments` varchar(255) DEFAULT NULL,
        `rdttrailersize` varchar(255) DEFAULT NULL,
        `rdttrailerpattern` varchar(255) DEFAULT NULL,
        `rdttrailerqty` int(11) DEFAULT NULL,
        `rdttrailercomments` varchar(255) DEFAULT NULL,
        `rdtdrivesize` varchar(255) DEFAULT NULL,
        `rdtdrivepattern` varchar(255) DEFAULT NULL,
        `rdtdriveqty` int(11) DEFAULT NULL,
        `rdtdrivecomments` varchar(255) DEFAULT NULL,
        `casingsize` varchar(255) DEFAULT NULL,
        `casingpattern` varchar(255) DEFAULT NULL,
        `casingqty` int(11) DEFAULT NULL,
        `casingcomments` varchar(255) DEFAULT NULL,
        `puncturesize` varchar(255) DEFAULT NULL,
        `puncturepattern` varchar(255) DEFAULT NULL,
        `punctureqty` int(11) DEFAULT NULL,
        `puncturecomments` varchar(255) DEFAULT NULL,
        `scrapsize` varchar(255) DEFAULT NULL,
        `scrappattern` varchar(255) DEFAULT NULL,
        `scrapqty` int(11) DEFAULT NULL,
        `scrapcomments` varchar(255) DEFAULT NULL,
        `rotatesize` varchar(255) DEFAULT NULL,
        `rotatepattern` varchar(255) DEFAULT NULL,
        `rotateqty` int(11) DEFAULT NULL,
        `rotatecomments` varchar(255) DEFAULT NULL,
        `tubesize` varchar(255) DEFAULT NULL,
        `tubepattern` varchar(255) DEFAULT NULL,
        `tubeqty` int(11) DEFAULT NULL,
        `tubecomments` varchar(255) DEFAULT NULL,
        `fitsteelalloylttrksize` varchar(255) DEFAULT NULL,
        `fitsteelalloylttrkpattern` varchar(255) DEFAULT NULL,
        `fitsteelalloylttrkqty` int(11) DEFAULT NULL,
        `fitsteelalloylttrkcomments` varchar(255) DEFAULT NULL,
        `balancestalloyltpowdersize` varchar(255) DEFAULT NULL,
        `balancestalloyltpowderpattern` varchar(255) DEFAULT NULL,
        `balancestalloyltpowderqty` int(11) DEFAULT NULL,
        `balancestalloyltpowdercomments` varchar(255) DEFAULT NULL,
        `rustbandsize` varchar(255) DEFAULT NULL,
        `rustbandpattern` varchar(255) DEFAULT NULL,
        `rustbandqty` int(11) DEFAULT NULL,
        `rustbandcomments` varchar(255) DEFAULT NULL,
        `valvestemsize` varchar(255) DEFAULT NULL,
        `valvestempattern` varchar(255) DEFAULT NULL,
        `valvestemqty` int(11) DEFAULT NULL,
        `valvestemcomments` varchar(255) DEFAULT NULL,
        `valveextsize` varchar(25) DEFAULT NULL,
        `valveextpattern` varchar(255) DEFAULT NULL,
        `valveextqty` int(11) DEFAULT NULL,
        `valveextcomments` varchar(255) DEFAULT NULL,
        `workperformedandcheckedby` varchar(255) DEFAULT NULL,
        `nutstentionedby` varchar(255) DEFAULT NULL,
        `customeralertnuts` int(11) DEFAULT NULL,
        `customeralertforkliftnuts` int(11) DEFAULT NULL,
        `nutstentionedbysignatureimage` varchar(1000) DEFAULT NULL,
        `customeralertothernuts` int(11) DEFAULT NULL,
        `customeralertothernutssignatureimage` varchar(1000) DEFAULT NULL,
        `customersignatureimage` LONGTEXT DEFAULT NULL,
        `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        `updated_at` TIMESTAMP,
        PRIMARY KEY (`parent_id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
        ");
//    }
//    catch (Exception $e)
//    {
//        //these tables were part of an older feature that
//        //never made it into the system.  Wrapping to catch
//        //a PDO exception if this extension is deployed somewhere
//    }

    $this->endSetup();
