<?php
   $make = Mage::helper('searchtyre')->getMakes();
?>

<div class="quick-finder relative" data-api-domain="https://api.vehiclelogic.com.au" data-api-key="<?php echo Mage::helper('searchtyre')->getToken(); ?>">
      <div class="row">
        <div class="large-12 columns">
           <ul class="tabs" data-tab="">
                <li class="tab-title active">
					<a href="#fond-wheels"><i class="fa fa-car"></i> Vehicle Type</a>
				</li>
           </ul>
           <div class="panel listing">
              <div class="tabs-content">
                 <div class="fond-tyres vehicle-type content active" id="fond-tyres">
                    <!-- Find Tyres -->
                    <form method="post" action="" data-action-format="/wheelsearch/[vehicle-name]/id/[vehicle-id]/y/[vehicle-year]">
						<input type="hidden" name="type" value="wheels">
						<input type="hidden" name="section" value="vehicles">
						<input type="hidden" name="category" value="42">
						<div class="row collapse">
							<div class="large-2 medium-2 columns form-wrapper">
								<select name="make-wheels" class="make-wheels" title="Select Make" data-pre-load="<?php echo Mage::getSingleton('core/session')->getTMakeF()?>">
									<option value="">Select Make</option>
									<?php foreach($make as $m=>$v) {?>
									<option value="<?php echo $m?>"><?php echo $v?></option>
									<?php }?>
								</select>
							</div>
							<div class="large-2 medium-2 columns form-wrapper">
								<select name="year-wheels" class="year-wheels" title="Select Year" data-pre-load="<?php echo Mage::getSingleton('core/session')->getTYearF()?>">
									<option value="">Select Year</option>
									<?php for($i=date("Y");$i>=1990;$i--) {?>
									<option value="<?php echo $i?>"><?php echo $i?></option>
									<?php }?>
								</select>
							</div>
							<div class="large-2 medium-2 columns form-wrapper">
								<select name="model-wheels" class="model-wheels" title="Select Model" data-pre-load="<?php echo Mage::getSingleton('core/session')->getTModelF()?>" disabled>
									<option value="">Select Model</option>
								</select>
								<div class="load-indicator"><i class="fa fa-refresh fa-spin"></i></div>
							</div>
							<div class="large-2 medium-2 columns form-wrapper" title="Select Series">
								<select name="series-wheels" class="series-wheels" data-pre-load="<?php echo Mage::getSingleton('core/session')->getSeriesF()?>" disabled>
									<option value="">Select Series</option>
								</select>
								<div class="load-indicator"><i class="fa fa-refresh fa-spin"></i></div>
							</div>
							<div class="large-2 medium-2 columns form-wrapper" title="Select Brands">
								<select name="brands-wheels" class="brands-wheels optional" disabled>
									<option value="">Select Brands</option>
								</select>
								<div class="load-indicator"><i class="fa fa-refresh fa-spin"></i></div>
							</div>
							<div class="large-2 medium-2 columns form-wrapper" title="Select Size">
								<select name="size-wheels" class="size-wheels optional" disabled>
									<option value="">Select Size</option>
								</select>
								<div class="load-indicator"><i class="fa fa-refresh fa-spin"></i></div>
							</div>
						</div>
                                                </form>
                                                
                        <div class="row">
                            <form method="post" action="/tyresearch">
							<div class="small-12 columns">
                                                                <input type="hidden" name="type_hidden" value="wheels">
								<input type="submit"  name="reset-btn" value="Clear Result" loc="/searchtyre/index/clear/type/wheels" class="reset-btn radius button expand" disabled>
								<div class="request-error">
									Sorry, there was a problem retrieving your requested data.
								</div>
							</div>
                            </form>
                       </div>
			
					   <input type="submit" class="hide" disabled>
                    </form>
					
					
					
                 </div>
                
           </div>
        </div>

	</div>


	</div>
	</div>
	
	<div class="wheel-content">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('promo-wheels-cdp')->toHtml(); ?>
	</div>

	<div class="wheel-list-header hide">
		<div class="row">
			<div class="columns medium-4">
				<h2>Select Your Wheels</h2>
			</div>
			<div class="columns medium-8">
				<ul class="inline-list right">
					<li>
						<label for="wheels-colour-filter">Filter by colour</label>
					</li>
					<li>
						<select id="wheels-colour-filter" class="wheels-colour-filter" disabled>
							<option value="All">All</option>
						</select>
					</li>
					<li><span class="wheel-list-count"><span></li>
				</ul>
			</div>
		</div>
	</div>
	
	
	<div class="wheel-list"></div>
	
	<div class="row">
		<div class="columns large-9 medium-12 hide-for-small-only">
		
			<div class="wheel-vehicle-demo hide">
				
				<div class="vehicle-holder"></div>
				
				<div class="vehicle-tools">
					<span>Colours:</span> 
					<ul class="colour-switch"></ul>

					<div class="vehicle-susension-wrapper">
						<span>Suspension:</span> 
					   <button class="set-vehicle-susension button radius small secondary" data-susension-state="standard">
							<i class="fa fa-arrows-v"></i> Standard
						</button>
					   <button class="set-vehicle-susension button radius small secondary" data-susension-state="lower">
							<i class="fa fa-level-down"></i> Lower
						</button>
					</div>
				</div>
				
			</div>
			
		</div>
		<div class="columns large-3 medium-12">
			
			<div class="wheel-active hide">
			
				<div class="product-item">

					<div class="info">
						<div class="row">
							<div class="small-3 columns">
							  <div class="product-image">
								<a title="" href="">
									<img src="" class="expand">
								</a>
							  </div>
							</div>
							<div class="small-9 columns product-slider-detail">
								<div class="product-details">
									<img src="" class="product-badge">
									<img src="images/gy-temp-logo.png" class="product-brand dealer-logo">
									<h5 class="product-title"><a href=""></a></h5>
									<ul class="select-wheel-size"></ul>									
									<a href="" class="button radius view-detials">View details</a>
								</div>
							</div>
						</div>
					</div>
					
					<div class="loader">
						<i class="fa fa-refresh fa-spin fa-2x"></i>
					</div>
					
					<div class="placeholder">
						<em>This product is currently unavailable</em>
					</div>
					
				</div>
			</div>
			
		</div>
	</div>
	
	<div class="wheels-notice hide"></div>
	
	<div id="add-product-modal" class="reveal-modal add-product-modal" data-rquest-url="/searchtyre/index/getConfigurable/product_id/" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	    <a class="close-reveal-modal" aria-label="Close"><i class="fa fa-times"></i></a>

	    <div class="popup-loading">
	        <i class="fa fa-refresh fa-spin fa-2x"></i>
	        <p>Loading product details...</p>
	    </div>

	    <div class="popup-form">

	        <h2 id="modalTitle" class="modalTitle">Please Select</h2>

	        <form action="/searchtyre/index/addcart" method="post">
				<input type="hidden" name="supperattr" value="311">
	            <div class="row field-size">
	                <div class="small-4 columns">
	                    Select Size:
	                </div>
	                <div class="small-8 columns">
	                    <select name="super_attribute" id="test" class="select-size"></select>
	                </div>
	            </div>
	            <div class="row field-quantity">
	                <div class="small-4 columns">
	                    Quantity:
	                </div>
	                <div class="small-8 columns">
	                    <select name="qty" class="select-quantity">
	                        <option>1</option>
	                        <option>2</option>
	                        <option>3</option>
	                        <option>4</option>
	                        <option>5</option>
	                        <option>6</option>
	                    </select>

	                </div>
	            </div>
	            <div class="row">
	                <div class="small-4 columns"></div>
	                <div class="small-8 columns">
	                    <input type="submit" value="Proceed to Cart" class="button radius">
	                </div>
	            </div>

	            <input type="hidden" class="model-field-product-id" name="productId" value="">

	        </form>

	    </div>

	    <div class="popup-error">
	        <h2>Failed to load product details</h2>
	        <p>
	            Message: <span class="error-msg"></span>
	        </p>
	    </div>

	</div>
