<!-- Quick Finder -->
<div class="quick-finder">

    <div class="row">
        <div class="large-4 columns">
            <ul class="tabs" data-tab>
                <li class="tab-title active"><a href="#fond-tyres">Find Tyres...</a></li>
                <li class="tab-title"><a href="#find-wheels">Find Wheels</a></li>
            </ul>
            <div class="panel">
                <div class="tabs-content">
                    <div class="content active" id="fond-tyres">
                        <div>
                            <h2>Vehicle Make</h2>
                            <form>
                                <select name="make" id="make">
                                    <option value="">Loading...</option>
                                </select>
                                <select name="year" id="year">
                                    <option value="">Select Year</option>
                                </select>
                                <select name="model" id="model">
                                    <option value="">Select Model</option>
                                </select>
                                <select name="series" id="series">
                                    <option value="">Select Series</option>
                                </select>
                                <input type="submit" value="Find Tyres">
                            </form>                            
                        </div>
                    </div>
                    <div class="content" id="find-wheels">
                        <p>Forms for Find Wheels</p>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>



<?php /*
 *

  <div>
  <h2>Vehicle Make</h2>
  <form>
  <select name="make" id="make">
  <option value="">Loading...</option>
  </select>

  <select name="year" id="year">
  <option value="">Select Year</option>
  </select>

  <select name="model" id="model">
  <option value="">Select Model</option>
  </select>


  <select name="series" id="series">
  <option value="">Select Series</option>
  </select>

  <input type="submit" value="Find Tyres">

  </form>
  <h2>Tire Size</h2>
  <form>
  <select name="width" id="width">
  <option value="">Loading...</option>
  </select>
  <select name="profile" id="profile">
  <option value="">Profile</option>
  </select>
  <select name="diameter" id="diameter">
  <option value="">Rim Diameter</option>
  </select>
  <input type="submit" value="Find Tyres">
  </form>
  </div>

 */ ?>