<?php
$store_id = Mage::app()->getStore()->getStoreId();
$auto_config = Mage::getModel('autocompleteplus_autosuggest/config')->getCollection()->getData();
$uuid = $auto_config[0]['licensekey'];
$query = Mage::app()->getRequest()->getParam('q');
?>
<!-- <div id="isp_search_result_page"></div> -->
<script>
    var __isp_fulltext_search_obj = {
        uuid: <?php echo '"' . $uuid . '"'; ?>,
        store_id: <?php echo $store_id; ?>,
        query: <?php echo '"' . $query . '"'; ?>
    };
</script>
    <?php
        $helper=Mage::helper('autocompleteplus_autosuggest');
        //$server_url = $helper->getServerUrl();
		$server_url = 'http://0-3vk.acp-magento.appspot.com/';
        $url = $server_url . '/ma_load_search_page?isp_platform=magento'; 
        $resp = $helper->sendCurl($url);
        $response_json = json_decode($resp);
        echo $response_json->html;
    ?>