<?php

require_once(__DIR__.'/../../../../../../../../app/Mage.php');


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-16 at 10:11:07.
 */
class Yireo_EmailOverride_Model_Email_TemplateTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Yireo_EmailOverride_Model_Email_Template
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        Mage::app();
        $this->object = Mage::getModel('core/email_template'); 
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Yireo_EmailOverride_Model_Email_Template
     */
    public function testYireoEmailTemplateClassOverridesCoreClass()
    {
       $actual_class_name = get_class($this->object);
       $expected_class_name = 'Yireo_EmailOverride_Model_Email_Template';
       // fwrite(STDOUT, print_r($this->object, true) . "\n"); // Dumps result to the output window. Useful for debugging       
       $this->assertEquals($expected_class_name, $actual_class_name);
    }
}
