<?php if (Mage::getStoreConfig('giftcard/giftcard/enabled', Mage::app()->getStore()->getStoreId())): ?>
  <?php
  $currentCustomer = Mage::getSingleton('customer/session')->getCustomer();
  $collection = Mage::getModel('kartparadigm_giftcard/giftcard')->getCollection()
          ->addFieldToFilter('receiver_mail', $currentCustomer->getEmail())
          ->addFieldToFilter('giftcard_status', 1)
          ->addOrder('giftcard_id', 'DESC');
  ?>
  <div class="form-field">
      <div class="discount gift-card-form">
          <form id="discount-form" action="<?php echo Mage::getBaseUrl() ?>giftcard/index/index" method="post">
              <div class="discount-form">

                <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                <label for="coupon_code"><?php echo $this->__('Choose Giftcard To Apply.') ?></label>
                <div class="input-box">
                  <?php
                  $quote = Mage::getSingleton('checkout/session')->getQuote();
                  $appliedcodes = $quote->getGiftcardCode();
                  ?>
                  <?php if ($collection->count() > 0): ?>
                  <select name="gccodes" id="gccodes" class="validate-select" title="Giftcard">
                    <option value=""> <?php echo $this->__('Select Giftcard Code') ?> </option>
                    <?php
                    foreach ($collection as $coll):
                        if (strpos($appliedcodes, $coll->getGiftcardCode()) !== false)
                            continue;
                        ?>
                        <option value="<?php echo $coll->getGiftcardCode() . ',' . $coll->getGiftcardBal(); ?>"><?php echo $coll->getGiftcardCode() . " (" . Mage::helper('core')->currency($coll['giftcard_bal']) . ")"; ?>
                        <?php endforeach; ?>
                    </option>
                  </select>
                          <?php endif; ?>   </div>
                  <?php endif; ?>

                  <input type="hidden" name="remove" id="remove-coupone" value="0" />

                  <div>
                    <label for="gc_code"><?php echo $this->__('Giftcard Code') ?>:</label>
                  </div>
                  <div>
                    <input type="text" class="input-text required-entry" id="gc_code" name="gc_code"  />
                    <?php
                    if (Mage::getStoreConfig('giftcard/giftcard/customamt_select', Mage::app()->getStore()->getStoreId())) {
                        echo "<br/>" . $this->__('Redeem Amount') . " : <input type='text' class='input-text required-entry' id='redeem_amt' name='redeem_amt'  />";
                    }
                    ?>
                  </div>

                  <div class="buttons-set">
                    <input type="submit" name="<?php echo $this->__('Apply Code') ?>" value="<?php echo $this->__('Redeem Code') ?>" class="button radius small"/>
                  </div>

                </div>

              </form>

              <?php if (Mage::getSingleton('checkout/session')->getQuote()->getGiftcardBalused() != 0): ?>
              <form action="<?php echo Mage::getBaseUrl() ?>giftcard/index/cancel" method="post">
                <ul class="no-bullet">
                <?php
                $gccodes = explode(",", Mage::getSingleton('checkout/session')->getQuote()->getGiftcardCode());
                $gcbals = explode(",", Mage::getSingleton('checkout/session')->getQuote()->getGiftcardBal());
                $gcbalused = explode(",", Mage::getSingleton('checkout/session')->getQuote()->getGiftcardBalused());
                $i = 0;
                foreach ($gccodes as $gccode) {
                    echo "<li><strong>" . $this->__('Code') . "</strong>: " . $gccode . $this->__('  Net Bal') . " : " . Mage::helper('core')->currency($gcbals[$i] - $gcbalused[$i], true, false) . "</li>";
                    $i++;
                }
                ?>
                </ul>
                <input type="submit" name="<?php echo $this->__('Cancel Code') ?>" value="Cancel Code" class="button radius small">
              </form>
        <?php endif;
    ?>
                </div>
                <?php endif; ?>
</div>
