<div class="extra-padding main-wrapper">
  <div class="main-container">
    <div class="row">
      <div class="large-12 columns">
        <h1 class="db-page-title">Create an Account</h1>
          <div class="row">
          <div class="column medium-6">

            <?php echo $this->getChildHtml('form_fields_before')?>
            <?php echo $this->getMessagesBlock()->toHtml() ?>

            <form data-abide id="register" action="<?php echo $this->getPostActionUrl() ?>" method="post">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

            <p><em>* Required Fields</em></p>

            <div class="row">
              <div class="columns small-12">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
              </div>
            </div>
                
    
            <?php $guestEmail = Mage::getSingleton('core/session')->getGuestEmail();?>
            <div class="row">
              <div class="columns small-12">
                 <label for="email_address">Email *</label>
                 <input type="email" name="email" id="email_address" value="<?php echo ($guestEmail ? $guestEmail : $this->escapeHtml($this->getFormData()->getEmail())) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" required />
                <small class="error">This is a required field - Please enter a valid email address</small>
              </div>
            </div>

          <div class="row">
            <div class="columns small-12">
              <label for="password">Password *</label>
              <input  type="password" name="password" id="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" class="validate-admin-password" required>
              <small class="error">This is a required field</small>
            </div>
          </div>
                
          <div class="row">
            <div class="columns small-12">
              <label for="confirmation">Confirm Password *</label>
              <input type="password" name="confirmation" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" required data-equalto="password">
              <small class="error">This is a required field - This password must match the one above</small>
            </div>
          </div>
                
          <?php if ($this->isNewsletterEnabled()): ?>
                  
          <div class="row">
            <div class="columns small-12">
              <label class="custom-field checkbox small-text margin-bottom-added">
                <input type="checkbox"  name="is_subscribed" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> />
                <span>Subscribe me to Beaurepaires Newsletter</span>
                <div class="indicator"></div>
              </label>
              
              <?php echo Mage::helper('newslettergroup')->getHiddenSubscribeAllFormInputs(); ?>
              
              <?php /* Extensions placeholder */ ?>
              <?php echo $this->getChildHtml('customer.form.register.newsletter')?>
      	   </div>
         </div>

          <div class="row">
              <div class="columns small-12">
                  <label class="custom-field checkbox small-text margin-bottom-added">
                    <input type="checkbox" name="termscondition" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Terms of use')) ?>" value="" id="termscondition" required />
                    <span><?php echo $this->__('I have read and I accept the ') ?><a href="<?php echo Mage::getBaseUrl() . 'terms-of-use'; ?>" target="_blank"><?php echo $this->__('terms of use') ?></a></span>
                    <div class="indicator"></div>
                    <small class="error">Please confirm that you have read  and accept the terms of use.</small>
                  </label>
              </div>
          </div>

          <div class="row">
              <div class="columns small-12">
                  <label class="custom-field checkbox small-text margin-bottom-added">
                    <input type="checkbox" name="privacypolicy" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Terms of the Privacy Policy')) ?>" class="" id="privacypolicy" required />
                    <span><?php echo $this->__('I have read and I accept the terms of the ') ?><a href="<?php echo Mage::getBaseUrl() . 'privacy-policy'; ?>" target="_blank"><?php echo $this->__('Privacy Policy') ?></a></span>
                    <div class="indicator"></div>                    
                    <small class="error">Please confirm that you have read  and accept the terms of the Privacy Policy.</small>
                  </label>
              </div>
          </div>
          
          <?php endif ?>
          <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button radius"><span><span><?php echo $this->__('Submit') ?></span></span></button>
          </form>


          <div class="row">
            <div class="columns small-12">
              <div class="line-seperator-with-text">
                  <hr>
                  <span>OR</span>
              </div>

              <p class="text-center">Login with your social account.</p>

              <?php echo $this->getLayout()->createBlock("pslogin/buttons")->setTemplate("pslogin/customer/form/login/buttons.phtml")->toHtml(); ?>
            </div>
          </div>
 
        </div>
              
      <div class="column medium-6">      
            <?php
            
              $key = "bft-Register-Important-Message";
              $blocks = Mage::getModel('dynamicblock/dynamicblock')->getAllBlocksPerPosition($key);
              
              if($blocks->count()>0) {
                 $blocks_data = $blocks->getFirstItem();
                 $identifier = $blocks_data->getIdentifier();

                 echo $this->getLayout()->createBlock('cms/block')->setBlockId($identifier)->toHtml();                   
              }

            ?>
          </div>
          </div>
      </div>
   </div>
  </div>  
</div>
    
<script language="javascript">var billingForm = new VarienForm('register');</script>