<?php 
$collection = Mage::helper("apdwidgets")->getBestSellers();
$store = Mage::app()->getStore();

?>
<?php $storeId = Mage::app()->getStore()->getId();?>
	<?php if (count($collection)>0): ?>
		<div class="popular-products">
			<h2 class="text-center small-only-text-left"><?php  echo $this->__('Popular Products') ?></h2>
			<div class="row collapse">
	          <div class="related-product-slider" data-equalizer>
	          	<?php echo $this->getPagerHtml() ?>
                        <?php $_columnCount = $this->getColumnCount(); ?>
	          	<?php $i=0; foreach ($collection as $data):
	          	
	          	//echo $data['final_product_id'].'<br>';
	          	
	          	$_item = Mage::getModel('catalog/product')->load($data['final_product_id']);
	          	//$_item1 = Mage::getModel('catalog/product')->loadByAttribute('sku',$data['sku']);
	          	
	          	
	          	if($_item) {
				
				
					
					
				
	          	
	          	$badge_th_img ="";
	          	$badge_th="";
	          	if($_item->getAttributeText('overlay')=='Best Seller')
                	 $badge_th = Mage::getBaseUrl('media').'theme/' . Mage::getStoreConfig('badges/badges/bestsellerth');
				elseif($_item->getAttributeText('overlay')=='New Arrival')
	                 $badge_th = Mage::getBaseUrl('media') .'theme/'. Mage::getStoreConfig('badges/badges/newth');
				elseif($_item->getAttributeText('overlay')=='On Sale')
	                 $badge_th = Mage::getBaseUrl('media') .'theme/'. Mage::getStoreConfig('badges/badges/onsaleth');

	            if(isset($badge_th) && $badge_th!='')
	                $badge_th_img = "<img class=\"product-badge\" src=\"$badge_th\">";
	          	
	          	
	           
	           $productUrl =  Mage::helper("apdwidgets")->getFullProductUrl($_item);
				
	          	
	          	 ?>
	            
				<div class="item medium-3 columns">
						<div class="row product-item">
							<div class="small-3 columns">
							  <div class="product-image">
								<a class="<?php echo $_item->getProductUrl()?>"  href="<?php echo $productUrl ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(100) ?>" class="expand" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" class="expand"></a>
							  </div>
							</div>
							<div data-equalizer-watch="" class="small-9 columns product-slider-detail">
							  <div class="product-details">
								<?php  $product = Mage::getModel('catalog/product')->load($_item->getId());?>
								<?php echo $badge_th_img ?>

								<?php $brand = $this->getSkinUrl('images/brands/' . strtolower($_item->getAttributeText('brand')) . '-logo.png');
								 // $url = getimagesize($brand);								
								 if (true || is_array($url)) {?>
								 <img src="<?php echo $brand;?>" alt="<?php echo $_item->getAttributeText('brand'); ?>" />
								 <?php }?>

								<h5 class="product-title"><a href="<?php echo $productUrl ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h5>
								<?php $ratings = Mage::getModel('review/review_summary')?>
								<?php $ratings = $ratings->setStoreId($storeId)->load($_item->getId());?>
								<?php if( $ratings['rating_summary'] != "" && $ratings['rating_summary'] != 0 ): ?>
								<div class="star-rating">
									 <?php echo Mage::helper('apdwidgets')->getStarHtmlFromRating($ratings['rating_summary']); ?>
								</div>
								 <?php endif; ?>
								<?php /*
								<!-- Hide price for phase 1 7/23/15 -->
								<div class="rrp">
									<span class="rrp-amount"><?php echo Mage::helper('core')->currency($_item->getPrice(), true, false); ?></span>
								</div>
								<div class="online-price">
									<span class="online-price"><?php echo Mage::helper('core')->currency($_item->getSpecialPrice(), true, false); ?><sub>ea</sub></span>
								</div>
								*/ ?>
							  </div>
							</div>
						</div>
					</div>
	          	
				
	            <?php 
	            $i++;
	          	if($i==12)
	          	break;		          
	            }
	            endforeach;?>
				
	          </div>
	        </div>
        </div>
	<?php endif;?>
