<?php /*
 *  APD reviews template
 *
 */ ?>

<?php $_items = Mage::helper('apdinteract_review')->getReviewsCollection()->getItems(); ?>
<div class="review-component">

    <?php if (count($_items)): ?>
		 <h3 class="section-title"><?php echo $this->__('Customer Reviews'); ?></h3>
		
        <?php foreach ($_items as $_review): ?>

            <div class="review-item">
                <h5><?php echo $this->htmlEscape($_review->getTitle()); ?></h5>

                
                    <?php 
                        $percentArray =  Mage::helper('apdinteract_review')->getStarRating($_review->getId());
                        $percent = 0;
                        if(isset($percentArray[0]['percent'])){
                            $percent = $percentArray[0]['percent'];
                        }
                    ?>
                    <?php if($percent >0):?>
                        
                        <div class="star-rating">
                            <?php echo Mage::helper('apdwidgets')->getStarHtmlFromRating($percent); ?>
                        </div>
                <?php endif; ?>

                <p><span><?php $this->htmlEscape($_review->getNickname()); ?></span>  <?php echo nl2br($this->htmlEscape($_review->getDetail())) ?></p>
            </div>

        <?php endforeach; ?>
    <?php endif; ?>

    <!-- review form -->
    <?php echo $this->getChildHtml('review_form'); ?>
</div>