<?php
$vehicle_helper = Mage::helper('apdinteract_vehicle');
?>
<div class="row">
    <div class="small-12 columns">
        <div class="row">
            <div class="small-12 columns">
                <h1 class="db-page-title"><?php echo $this->__('Mobility Data') ?></h1>

                <?php $msg = $this->__('Please contact your nearest Beaurepaires store by calling 13 23 81 or calling 
                             1800 106 010 connects you to an emergency response centre day or night,
                             7 days a week');
                ?>
                <?php $vehicle_collection = $vehicle_helper->vehicleCollection(); ?>
                <?php if($vehicle_collection->getSize()> 0): ?>
                <div class="row">
                    <div class="small-4 columns">
                        <select id="vehicleSelector">
                            <option value="" disabled selected>Select Vehicle</option>
                            <?php foreach($vehicle_collection as $item): ?>
                                <option value="<?php echo $item->getUrl() ?>"><?php echo $item->getRegistration() ?></option>
                            <?php endforeach; ?>
                        </select>
                        <div class="load-indicator hide  custom"><i class="fa fa-refresh fa-spin"></i></div>
                    </div>
                </div>
                <div class="row">
                    <div class="columns">
                        <p class="vehicle-empty hide"><?php echo $msg ?></p>
                        <iframe width="100%" data-emptymsg="<?php echo $msg ?>" scr="" alt="sample" height="500px" frameborder="0" id="vehicleIframe">w</iframe>
                    </div>
                </div>
                <?php else: ?>
                <div class="row">
                    <div class="columns">
                        <p class="vehicle-empty"><?php echo $msg ?></p>
                    </div>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
