<?php
/**
 *
 * @category    design
 * @package     default_default
 * @author     Fsite
 */
?>
<ul class="form-list no-bullet">
<?php if( $this->hasGroups() ): ?>

        <?php
            $_groups       = $this->getGroups();
            $_groupsCount  = count( $_groups );
            $_counter = 0;
            $_subscribersGroupIds = $this->getNewsletterGroupId();
            $_groupIds = explode( ',', $_subscribersGroupIds );
        ?>
        <?php foreach ($_groups as $_group): $_id = $_group->getId(); $_counter++; ?>
            <?php
                // Do not display sub groups at this level
                if ( $_group->getParentGroupId() > 0 ) :
                        continue;
                endif;
            ?>

                    <?php if ( $_group->getSubGroups() ): ?>
                        <?php
                            $_childCounter = $_counter;
                        ?>
                        <h4 class="legend db-sub-page-title"><?php echo $_group->getGroupName() ?></h4>
                        <?php foreach ( $_group->getSubGroups() as $_child ): ?>
                         <li class="control">
                            <?php in_array($_child->getId(), $_groupIds) ? $_checked = true : $_checked = false; ?>
                            <?php $groupName = $this->htmlEscape(Mage::helper('newslettergroup')->hidePrefixFromNewsletterName($_child->getGroupName())); ?>
                            <input id="is_subscribed_<?php echo $_child->getId() ?>" value="<?php echo $_child->getId() ?>" type="checkbox" name="is_subscribed[]" title="<?php echo $groupName ?>" <?php if($_checked): ?>checked="checked"<?php endif; ?> />
                            <label for="is_subscribed_<?php echo $_child->getId() ?>"><?php echo $groupName ?></label>
                            <?php  $_childCounter++; ?>
                         </li>
                        <?php endforeach; ?>

                    <?php else: ?>
                        <?php /*?>
                        <?php if ($_groupsCount > 1): ?>
                        <?php $groupName = $this->htmlEscape(Mage::helper('newslettergroup')->hidePrefixFromNewsletterName($_group->getGroupName())); ?>
                        <?php in_array($_id, $_groupIds) ? $_checked = true : $_checked = false; ?>
                        <input id="is_subscribed_<?php echo $_id ?>" value="<?php echo $_id ?>" type="checkbox" name="is_subscribed[]" title="<?php echo $groupName ?>" <?php if($_checked): ?>checked="checked"<?php endif; ?> />
                        <label for="is_subscribed_<?php echo $_id ?>"><?php echo $groupName ?></label>
                        <?php endif;?>
                        <?php */ ?>
                    <?php endif;?>

        <?php endforeach; ?>

<?php endif; ?>

</ul>