<?php

require_once(__DIR__.'/../../../../../../../app/Mage.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-04 at 11:55:42.
 */
class ApdInteract_Customreindex_Model_ObserverTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var ApdInteract_Customreindex_Model_Observer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        Mage::app();        
        $this->model = Mage::getModel('customreindex/observer');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers ApdInteract_Customreindex_Model_Observer::runindexer
     */
    public function testRunindexer()
    {        
        $result = $this->model->runindexer();
        $this->assertTrue($result, 'No reindex processes appear to have run');
    }
}
