<?php
/**
 * Bestseller Products block template
 *
 * @see Mage_Catalog_Block_Product_Bestseller
 */
?>
<?php $collection = $this->getCollection(); ?>
<?php $overlay_text = ''; ?>
<?php if (count($collection)>0): ?>
    <div class="popular-products">
        <h2 class="text-center small-only-text-left"><?php  echo $this->__('Popular Products') ?></h2>
        <div class="row collapse">
            <div class="related-product-slider" data-equalizer>
                <?php echo $this->getPagerHtml() ?>
                <?php $_columnCount = $this->getColumnCount(); ?>
                <?php foreach ($collection as $product):
 
                    $badge_th_img ="";
                    $badge_th="";
                    $badge_th = Mage::helper('apdinteract_catalog')->getBadgeSrc($product['overlay'], $thumb = true);

                    $overlay_text = $product['overlay'];
                    $catalogue = str_replace(' ', '', strtolower($overlay_text));
                    if (strpos($catalogue, 'new') !== false){
                        $catalogue = 'new';
                    }
                    $badge_th_img = "<div class=\"product-badge-block small {$catalogue}\">{$overlay_text}</div>";

                    $productUrl =  $product['product_url'];
                    ?>

                    <div class="item medium-3 columns">
                        <div class="row product-item">
                            <div class="small-3 columns">
                                <div class="product-image">
                                    <a class="<?php echo $productUrl ?>"  href="<?php echo $productUrl ?>"><img src="<?php echo $product['thumbnail'] ?>" class="expand" alt="<?php echo $this->escapeHtml($product['name']) ?>" class="expand"></a>
                                </div>
                            </div>
                            <div data-equalizer-watch="" class="small-9 columns product-slider-detail">
                                <div class="product-details">
                                    <?php echo $badge_th_img ?>

                                    <?php $brand = $this->getSkinUrl('images/brands/' . strtolower($product['brand']) . '-logo.png');
                                    // $url = getimagesize($brand);
                                    if (true || is_array($url)) {?>
                                        <img src="<?php echo $brand;?>" alt="<?php echo $product['brand']; ?>" />
                                    <?php }?>

                                    <h5 class="product-title"><a href="<?php echo $productUrl ?>"><?php echo $this->escapeHtml($product['name']) ?></a></h5>

                                    <?php $ratings = Mage::getModel('review/review_summary')?>
                                    <?php $ratings = $ratings->setStoreId($storeId)->load($product['product_id']);?>
                                    <?php if( $ratings['rating_summary'] != "" && $ratings['rating_summary'] != 0 ): ?>
                                        <div class="star-rating">
                                            <?php echo Mage::helper('apdwidgets')->getStarHtmlFromRating($ratings['rating_summary']); ?>
                                        </div>
                                    <?php endif; ?>
                                    <?php
                                    $rrp = $product['rrp'];
                                    $specialPrice = $product['special_price'];
                                    $onlinePrice = $product['online_price'];
                                    $from =$product['from'];
                                    $isConfigurable = $product['is_configurable'];
                                    ?>

                                    <?php if ($rrp > $onlinePrice && $onlinePrice != 0 ):?>
                                        <div class="price-label">RRP:</div>
                                        <div class="rrp">
                                            <span class="rrp-amount"><?php echo $rrp?>/ea</span>
                                        </div>
                                        <div class="price-label">Online <?php echo $from?></div>
                                        <div class="online-price">
                                            <span class="online-price"><?php echo $onlinePrice?>/ea</span>
                                        </div>
                                    <?php elseif (($onlinePrice != 0  && ($specialPrice == null || $specialPrice == 0 ))):?>
                                        <div class="price-label">Online <?php echo $from?></div>
                                        <div class="online-price">
                                            <span class="online-price"><?php echo $onlinePrice?>/ea</span>
                                        </div>
                                    <?php elseif (($onlinePrice >= $rrp) || ($onlinePrice == 0)):?>
                                        <div class="price-label">Request price</div>
                                    <?php endif;?>

                                    <?php $productCompareHelper = $this->helper('catalog/product_compare');
                                    $_compareItems = $productCompareHelper->getItemCount() > 0 ? $productCompareHelper->getItemCollection() : array();
                                    $compareProductIds = array();

                                    foreach ($_compareItems as $item) {
                                        $compareProductIds[] = $item->getId();
                                    }
                                    ?>

                                    <?php //if ($_compareItems && (in_array($product['product_id'], $compareProductIds))): ?>
                                        <!--<a href="javascript:;" class="link-compare"  onclick="popWin('<?php //echo $productCompareHelper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><?php //echo $this->__('View Compare')?></a>-->
                                    <?php //elseif($_compareUrl = $product['add_compare_url']):?>
                                        <!--<a href="<?php //echo $_compareUrl?>" class="link-compare"><?php //echo $this->__('Add to Compare')?></a>-->
                                    <?php //endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php
                endforeach;?>

            </div>
        </div>
    </div>
<?php endif;?>
