<?php
require_once(__DIR__ . '/../../../../../../../app/Mage.php');
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-15 at 07:56:11.
 */
class ApdInteract_Rel_Helper_DataTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ApdInteract_Rel_Helper_Data
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        Mage::app();
        $this->object = Mage::helper('apdinteract_rel');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    private function _dbr()
    {
        return Mage::getSingleton('core/resource')->getConnection('core/read');
    }
    
     /** @test
     * @covers ApdInteract_Rel_Helper_Data
     * Check if there are null values for URL field in apdinteract_canonical_url table.
     */
    public function checkUrlValues()
    {
        $canonical = $this->object->checkUrlValues();        
        $this->assertTrue($canonical,"Url column cannot be null, kindly check all data in Apdinteract_Canonical_Table");
    }

}
